
INSERT INTO Instructor ('email', 'name')
VALUES  ('danielleburgess@gmail.com', ' Danielle Burgess'),
VALUES  ('danielleburgess@gmail.com', ' Danielle Burgess'),
VALUES  ('deannaharris@example.net', ' Deanna Harris'),
VALUES  ('deannaharris@example.net', ' Deanna Harris'),
VALUES  ('josephandrews@hotmail.com', ' Joseph Andrews'),
VALUES  ('josephandrews@hotmail.com', ' Joseph Andrews'),
VALUES  ('greglopez@example.com', ' Greg Lopez'),
VALUES  ('greglopez@example.com', ' Greg Lopez'),
VALUES  ('briansloan@example.com', ' Brian Sloan'),
VALUES  ('briansloan@example.com', ' Brian Sloan'),
VALUES  ('nancyalexander@example.com', ' Nancy Alexander'),
VALUES  ('nancyalexander@example.com', ' Nancy Alexander'),
VALUES  ('nancyalexander@example.com', ' Nancy Alexander'),
VALUES  ('daniellopez@hotmail.com', ' Daniel Lopez'),
VALUES  ('daniellopez@hotmail.com', ' Daniel Lopez'),
VALUES  ('daniellopez@hotmail.com', ' Daniel Lopez'),
VALUES  ('mrs.leslielane@example.com', ' Mrs. Leslie Lane'),
VALUES  ('mrs.leslielane@example.com', ' Mrs. Leslie Lane'),
VALUES  ('mrs.leslielane@example.com', ' Mrs. Leslie Lane'),
VALUES  ('anthonymyers@example.com', ' Anthony Myers'),
VALUES  ('anthonymyers@example.com', ' Anthony Myers'),
VALUES  ('stephenburnett@gmail.com', ' Stephen Burnett'),
VALUES  ('stephenburnett@gmail.com', ' Stephen Burnett'),
VALUES  ('stephenburnett@gmail.com', ' Stephen Burnett'),
VALUES  ('saramcdonald@hotmail.com', ' Sara Mcdonald'),
VALUES  ('johnmorris@example.com', ' John Morris'),
VALUES  ('johnmorris@example.com', ' John Morris'),
VALUES  ('peterwilliams@gmail.com', ' Peter Williams'),
VALUES  ('michaeltrujillo@hotmail.com', ' Michael Trujillo'),
VALUES  ('michaeltrujillo@hotmail.com', ' Michael Trujillo'),
VALUES  ('scottlara@example.com', ' Scott Lara'),
VALUES  ('scottlara@example.com', ' Scott Lara'),
VALUES  ('ericburgess@hotmail.com', ' Eric Burgess'),
VALUES  ('ericburgess@hotmail.com', ' Eric Burgess'),
VALUES  ('jessicaponce@example.net', ' Jessica Ponce'),
VALUES  ('jessicaponce@example.net', ' Jessica Ponce'),
VALUES  ('mr.michaelkeithdds@example.com', ' Mr. Michael Keith DDS'),
VALUES  ('mr.michaelkeithdds@example.com', ' Mr. Michael Keith DDS'),
VALUES  ('josephglass@gmail.com', ' Joseph Glass'),
VALUES  ('josephglass@gmail.com', ' Joseph Glass'),
VALUES  ('christophergalvan@example.net', ' Christopher Galvan'),
VALUES  ('christophergalvan@example.net', ' Christopher Galvan'),
VALUES  ('christophergalvan@example.net', ' Christopher Galvan'),
VALUES  ('gregorybrock@example.net', ' Gregory Brock'),
VALUES  ('justingrantjr.@example.net', ' Justin Grant Jr.'),
VALUES  ('justingrantjr.@example.net', ' Justin Grant Jr.'),
VALUES  ('roseryan@hotmail.com', ' Rose Ryan'),
VALUES  ('roseryan@hotmail.com', ' Rose Ryan'),
VALUES  ('roseryan@hotmail.com', ' Rose Ryan'),
VALUES  ('stephaniepreston@example.com', ' Stephanie Preston'),
VALUES  ('stephaniepreston@example.com', ' Stephanie Preston'),
VALUES  ('stephaniepreston@example.com', ' Stephanie Preston'),
VALUES  ('michaelvelasquez@gmail.com', ' Michael Velasquez'),
VALUES  ('michaelvelasquez@gmail.com', ' Michael Velasquez'),
VALUES  ('danielfrey@example.net', ' Daniel Frey'),
VALUES  ('danielfrey@example.net', ' Daniel Frey'),
VALUES  ('karenmueller@example.net', ' Karen Mueller'),
VALUES  ('karenmueller@example.net', ' Karen Mueller'),
VALUES  ('karenmueller@example.net', ' Karen Mueller'),
VALUES  ('elizabethhartman@example.com', ' Elizabeth Hartman'),
VALUES  ('philipluna@example.com', ' Philip Luna'),
VALUES  ('philipluna@example.com', ' Philip Luna'),
VALUES  ('philipluna@example.com', ' Philip Luna'),
VALUES  ('timothynelson@example.net', ' Timothy Nelson'),
VALUES  ('timothynelson@example.net', ' Timothy Nelson'),
VALUES  ('timothynelson@example.net', ' Timothy Nelson'),
VALUES  ('jeremysmith@example.net', ' Jeremy Smith'),
VALUES  ('jeremysmith@example.net', ' Jeremy Smith'),
VALUES  ('jeremysmith@example.net', ' Jeremy Smith'),
VALUES  ('barbarasmith@example.com', ' Barbara Smith'),
VALUES  ('barbarasmith@example.com', ' Barbara Smith'),
VALUES  ('davidhodge@hotmail.com', ' David Hodge'),
VALUES  ('davidhodge@hotmail.com', ' David Hodge'),
VALUES  ('timothywilliamson@example.com', ' Timothy Williamson'),
VALUES  ('timothywilliamson@example.com', ' Timothy Williamson'),
VALUES  ('ralphjackson@hotmail.com', ' Ralph Jackson'),
VALUES  ('ralphjackson@hotmail.com', ' Ralph Jackson'),
VALUES  ('taylorryan@hotmail.com', ' Taylor Ryan'),
VALUES  ('taylorryan@hotmail.com', ' Taylor Ryan'),
VALUES  ('travisthomas@hotmail.com', ' Travis Thomas'),
VALUES  ('travisthomas@hotmail.com', ' Travis Thomas'),
VALUES  ('leahphelps@example.com', ' Leah Phelps'),
VALUES  ('leahphelps@example.com', ' Leah Phelps'),
VALUES  ('leahphelps@example.com', ' Leah Phelps'),
VALUES  ('rubenhubbard@example.com', ' Ruben Hubbard'),
VALUES  ('rubenhubbard@example.com', ' Ruben Hubbard'),
VALUES  ('samanthasullivan@example.net', ' Samantha Sullivan'),
VALUES  ('samanthasullivan@example.net', ' Samantha Sullivan'),
VALUES  ('erikacampbell@hotmail.com', ' Erika Campbell'),
VALUES  ('erikacampbell@hotmail.com', ' Erika Campbell'),
VALUES  ('erikacampbell@hotmail.com', ' Erika Campbell'),
VALUES  ('daniellegentry@example.net', ' Danielle Gentry'),
VALUES  ('daniellegentry@example.net', ' Danielle Gentry'),
VALUES  ('daniellegentry@example.net', ' Danielle Gentry'),
VALUES  ('edwardroberts@example.net', ' Edward Roberts'),
VALUES  ('edwardroberts@example.net', ' Edward Roberts'),
VALUES  ('edwardroberts@example.net', ' Edward Roberts'),
VALUES  ('jillianho@example.com', ' Jillian Ho'),
VALUES  ('jillianho@example.com', ' Jillian Ho'),
VALUES  ('jillianho@example.com', ' Jillian Ho'),
VALUES  ('karenmiller@example.net', ' Karen Miller'),
VALUES  ('karenmiller@example.net', ' Karen Miller'),
VALUES  ('karenmiller@example.net', ' Karen Miller'),
VALUES  ('gabriellarson@hotmail.com', ' Gabriel Larson'),
VALUES  ('gabriellarson@hotmail.com', ' Gabriel Larson'),
VALUES  ('nicoleholland@example.com', ' Nicole Holland'),
VALUES  ('nicoleholland@example.com', ' Nicole Holland'),
VALUES  ('nicoleholland@example.com', ' Nicole Holland'),
VALUES  ('allisoncross@gmail.com', ' Allison Cross'),
VALUES  ('allisoncross@gmail.com', ' Allison Cross'),
VALUES  ('laurajones@example.com', ' Laura Jones'),
VALUES  ('laurajones@example.com', ' Laura Jones'),
VALUES  ('jodyparker@example.com', ' Jody Parker'),
VALUES  ('jodyparker@example.com', ' Jody Parker'),
VALUES  ('michelleanthony@example.net', ' Michelle Anthony'),
VALUES  ('michelleanthony@example.net', ' Michelle Anthony'),
VALUES  ('michelleanthony@example.net', ' Michelle Anthony'),
VALUES  ('kevintanner@example.com', ' Kevin Tanner'),
VALUES  ('adamwilliams@example.net', ' Adam Williams'),
VALUES  ('adamwilliams@example.net', ' Adam Williams'),
VALUES  ('jessicacallahan@hotmail.com', ' Jessica Callahan'),
VALUES  ('jessicacallahan@hotmail.com', ' Jessica Callahan'),
VALUES  ('tiffanymartinez@gmail.com', ' Tiffany Martinez'),
VALUES  ('tiffanymartinez@gmail.com', ' Tiffany Martinez'),
VALUES  ('amandaandrews@example.net', ' Amanda Andrews'),
VALUES  ('amandaandrews@example.net', ' Amanda Andrews'),
VALUES  ('jamesmedina@gmail.com', ' James Medina'),
VALUES  ('jamesmedina@gmail.com', ' James Medina'),
VALUES  ('jamesmedina@gmail.com', ' James Medina'),
VALUES  ('vanessagreen@example.net', ' Vanessa Green'),
VALUES  ('vanessagreen@example.net', ' Vanessa Green'),
VALUES  ('vanessagreen@example.net', ' Vanessa Green'),
VALUES  ('anthonybrewer@example.com', ' Anthony Brewer'),
VALUES  ('melissaortega@example.net', ' Melissa Ortega'),
VALUES  ('melissaortega@example.net', ' Melissa Ortega'),
VALUES  ('melissaortega@example.net', ' Melissa Ortega'),
VALUES  ('williamshepard@gmail.com', ' William Shepard'),
VALUES  ('williamshepard@gmail.com', ' William Shepard'),
VALUES  ('williamshepard@gmail.com', ' William Shepard'),
VALUES  ('laurapace@hotmail.com', ' Laura Pace'),
VALUES  ('laurapace@hotmail.com', ' Laura Pace'),
VALUES  ('laurapace@hotmail.com', ' Laura Pace'),
VALUES  ('stephaniebean@hotmail.com', ' Stephanie Bean'),
VALUES  ('stephaniebean@hotmail.com', ' Stephanie Bean'),
VALUES  ('troybush@example.net', ' Troy Bush'),
VALUES  ('troybush@example.net', ' Troy Bush'),
VALUES  ('troybush@example.net', ' Troy Bush'),
VALUES  ('carolhaynes@example.com', ' Carol Haynes'),
VALUES  ('carolhaynes@example.com', ' Carol Haynes'),
VALUES  ('angelshelton@example.com', ' Angel Shelton'),
VALUES  ('angelshelton@example.com', ' Angel Shelton'),
VALUES  ('angelshelton@example.com', ' Angel Shelton'),
VALUES  ('taylorgraham@hotmail.com', ' Taylor Graham'),
VALUES  ('taylorgraham@hotmail.com', ' Taylor Graham'),
VALUES  ('taylorgraham@hotmail.com', ' Taylor Graham'),
VALUES  ('patriciariley@example.net', ' Patricia Riley'),
VALUES  ('patriciariley@example.net', ' Patricia Riley'),
VALUES  ('patriciariley@example.net', ' Patricia Riley'),
VALUES  ('manuelserrano@example.com', ' Manuel Serrano'),
VALUES  ('nicolelane@example.com', ' Nicole Lane'),
VALUES  ('nicolelane@example.com', ' Nicole Lane'),
VALUES  ('colleenaguilar@example.com', ' Colleen Aguilar'),
VALUES  ('colleenaguilar@example.com', ' Colleen Aguilar'),
VALUES  ('colleenaguilar@example.com', ' Colleen Aguilar'),
VALUES  ('heathercordova@example.com', ' Heather Cordova'),
VALUES  ('heathercordova@example.com', ' Heather Cordova'),
VALUES  ('mrs.danielleyoung@example.com', ' Mrs. Danielle Young'),
VALUES  ('mrs.danielleyoung@example.com', ' Mrs. Danielle Young'),
VALUES  ('derekharrell@example.com', ' Derek Harrell'),
VALUES  ('derekharrell@example.com', ' Derek Harrell'),
VALUES  ('dennismcdaniel@example.com', ' Dennis Mcdaniel'),
VALUES  ('dennismcdaniel@example.com', ' Dennis Mcdaniel'),
VALUES  ('dennismcdaniel@example.com', ' Dennis Mcdaniel'),
VALUES  ('davidthornton@example.com', ' David Thornton'),
VALUES  ('davidthornton@example.com', ' David Thornton'),
VALUES  ('craigrobinson@example.com', ' Craig Robinson'),
VALUES  ('craigrobinson@example.com', ' Craig Robinson'),
VALUES  ('timothymartin@gmail.com', ' Timothy Martin'),
VALUES  ('kevinwilliams@gmail.com', ' Kevin Williams'),
VALUES  ('kevinwilliams@gmail.com', ' Kevin Williams'),
VALUES  ('derekrichardson@gmail.com', ' Derek Richardson'),
VALUES  ('codynguyen@example.net', ' Cody Nguyen'),
VALUES  ('codynguyen@example.net', ' Cody Nguyen'),
VALUES  ('codynguyen@example.net', ' Cody Nguyen'),
VALUES  ('hannahhall@hotmail.com', ' Hannah Hall'),
VALUES  ('hannahhall@hotmail.com', ' Hannah Hall'),
VALUES  ('hannahhall@hotmail.com', ' Hannah Hall'),
VALUES  ('crystalkim@example.net', ' Crystal Kim'),
VALUES  ('andreagilmoremd@example.com', ' Andrea Gilmore MD'),
VALUES  ('andreagilmoremd@example.com', ' Andrea Gilmore MD'),
VALUES  ('elizabethhubbard@example.net', ' Elizabeth Hubbard'),
VALUES  ('elizabethhubbard@example.net', ' Elizabeth Hubbard'),
VALUES  ('elizabethhubbard@example.net', ' Elizabeth Hubbard'),
VALUES  ('jenniferwilkerson@gmail.com', ' Jennifer Wilkerson'),
VALUES  ('jenniferwilkerson@gmail.com', ' Jennifer Wilkerson'),
VALUES  ('paulashaffer@example.com', ' Paula Shaffer'),
VALUES  ('paulashaffer@example.com', ' Paula Shaffer'),
VALUES  ('paulashaffer@example.com', ' Paula Shaffer'),
VALUES  ('kevinholmes@example.com', ' Kevin Holmes'),
VALUES  ('kevinholmes@example.com', ' Kevin Holmes'),
VALUES  ('kevinholmes@example.com', ' Kevin Holmes'),
VALUES  ('brandoncompton@example.net', ' Brandon Compton'),
VALUES  ('brandoncompton@example.net', ' Brandon Compton'),
VALUES  ('brandoncompton@example.net', ' Brandon Compton'),
VALUES  ('arianagreer@hotmail.com', ' Ariana Greer'),
VALUES  ('arianagreer@hotmail.com', ' Ariana Greer'),
VALUES  ('arianagreer@hotmail.com', ' Ariana Greer'),
VALUES  ('kimberlypatton@example.com', ' Kimberly Patton'),
VALUES  ('kimberlypatton@example.com', ' Kimberly Patton'),
VALUES  ('bethmanning@hotmail.com', ' Beth Manning'),
VALUES  ('bethmanning@hotmail.com', ' Beth Manning'),
VALUES  ('rubenrobbins@example.net', ' Ruben Robbins'),
VALUES  ('rubenrobbins@example.net', ' Ruben Robbins'),
VALUES  ('kellydavis@example.net', ' Kelly Davis'),
VALUES  ('kellydavis@example.net', ' Kelly Davis'),
VALUES  ('joelsmith@gmail.com', ' Joel Smith'),
VALUES  ('joelsmith@gmail.com', ' Joel Smith'),
VALUES  ('staceypearson@gmail.com', ' Stacey Pearson'),
VALUES  ('staceypearson@gmail.com', ' Stacey Pearson'),
VALUES  ('billysalasdvm@gmail.com', ' Billy Salas DVM'),
VALUES  ('billysalasdvm@gmail.com', ' Billy Salas DVM'),
VALUES  ('davidsampson@example.com', ' David Sampson'),
VALUES  ('davidsampson@example.com', ' David Sampson'),
VALUES  ('emmasolomon@example.net', ' Emma Solomon'),
VALUES  ('emmasolomon@example.net', ' Emma Solomon'),
VALUES  ('emmasolomon@example.net', ' Emma Solomon'),
VALUES  ('lesliemadden@example.com', ' Leslie Madden'),
VALUES  ('lesliemadden@example.com', ' Leslie Madden'),
VALUES  ('lesliemadden@example.com', ' Leslie Madden'),
VALUES  ('kylebates@example.com', ' Kyle Bates'),
VALUES  ('kylebates@example.com', ' Kyle Bates'),
VALUES  ('carlyturner@gmail.com', ' Carly Turner'),
VALUES  ('carlyturner@gmail.com', ' Carly Turner'),
VALUES  ('sophiaholden@example.net', ' Sophia Holden'),
VALUES  ('sophiaholden@example.net', ' Sophia Holden'),
VALUES  ('parkerbuckley@hotmail.com', ' Parker Buckley'),
VALUES  ('parkerbuckley@hotmail.com', ' Parker Buckley'),
VALUES  ('jamesyoung@example.net', ' James Young'),
VALUES  ('douglascase@gmail.com', ' Douglas Case'),
VALUES  ('douglascase@gmail.com', ' Douglas Case'),
VALUES  ('peggyhess@example.com', ' Peggy Hess'),
VALUES  ('peggyhess@example.com', ' Peggy Hess'),
VALUES  ('peggyhess@example.com', ' Peggy Hess'),
VALUES  ('franciswilson@example.com', ' Francis Wilson'),
VALUES  ('franciswilson@example.com', ' Francis Wilson'),
VALUES  ('jenniferbrown@example.com', ' Jennifer Brown'),
VALUES  ('jenniferbrown@example.com', ' Jennifer Brown'),
VALUES  ('jenniferbrown@example.com', ' Jennifer Brown'),
VALUES  ('lisabarnes@gmail.com', ' Lisa Barnes'),
VALUES  ('daniellechavez@example.net', ' Danielle Chavez'),
VALUES  ('daniellechavez@example.net', ' Danielle Chavez'),
VALUES  ('daniellechavez@example.net', ' Danielle Chavez'),
VALUES  ('eduardoburns@example.net', ' Eduardo Burns'),
VALUES  ('eduardoburns@example.net', ' Eduardo Burns'),
VALUES  ('troymorrison@gmail.com', ' Troy Morrison'),
VALUES  ('troymorrison@gmail.com', ' Troy Morrison'),
VALUES  ('scottmiller@gmail.com', ' Scott Miller'),
VALUES  ('scottmiller@gmail.com', ' Scott Miller'),
VALUES  ('cynthiabailey@hotmail.com', ' Cynthia Bailey'),
VALUES  ('cynthiabailey@hotmail.com', ' Cynthia Bailey'),
VALUES  ('cynthiabailey@hotmail.com', ' Cynthia Bailey'),
VALUES  ('jackwilliams@example.com', ' Jack Williams'),
VALUES  ('jackwilliams@example.com', ' Jack Williams'),
VALUES  ('jackwilliams@example.com', ' Jack Williams'),
VALUES  ('oscarcole@example.com', ' Oscar Cole'),
VALUES  ('oscarcole@example.com', ' Oscar Cole'),
VALUES  ('jonathantaylor@gmail.com', ' Jonathan Taylor'),
VALUES  ('jonathantaylor@gmail.com', ' Jonathan Taylor'),
VALUES  ('tracyrodriguez@hotmail.com', ' Tracy Rodriguez'),
VALUES  ('tracyrodriguez@hotmail.com', ' Tracy Rodriguez'),
VALUES  ('tracyrodriguez@hotmail.com', ' Tracy Rodriguez'),
VALUES  ('jameswilliams@example.com', ' James Williams'),
VALUES  ('jameswilliams@example.com', ' James Williams'),
VALUES  ('thomasfisher@example.net', ' Thomas Fisher'),
VALUES  ('thomasfisher@example.net', ' Thomas Fisher'),
VALUES  ('ashleysims@hotmail.com', ' Ashley Sims'),
VALUES  ('ashleysims@hotmail.com', ' Ashley Sims'),
VALUES  ('todddavis@example.net', ' Todd Davis'),
VALUES  ('todddavis@example.net', ' Todd Davis'),
VALUES  ('tanyagarcia@example.net', ' Tanya Garcia'),
VALUES  ('tanyagarcia@example.net', ' Tanya Garcia'),
VALUES  ('sarawoods@example.com', ' Sara Woods'),
VALUES  ('sarawoods@example.com', ' Sara Woods'),
VALUES  ('sarawoods@example.com', ' Sara Woods'),
VALUES  ('michelerice@example.net', ' Michele Rice'),
VALUES  ('michelerice@example.net', ' Michele Rice'),
VALUES  ('tinamoore@gmail.com', ' Tina Moore'),
VALUES  ('tinamoore@gmail.com', ' Tina Moore'),
VALUES  ('tinamoore@gmail.com', ' Tina Moore'),
VALUES  ('johnnygrant@example.net', ' Johnny Grant'),
VALUES  ('johnnygrant@example.net', ' Johnny Grant'),
VALUES  ('adampeterson@hotmail.com', ' Adam Peterson'),
VALUES  ('adampeterson@hotmail.com', ' Adam Peterson'),
VALUES  ('katherinemendez@hotmail.com', ' Katherine Mendez'),
VALUES  ('katherinemendez@hotmail.com', ' Katherine Mendez'),
VALUES  ('jasonphillips@example.com', ' Jason Phillips'),
VALUES  ('jasonphillips@example.com', ' Jason Phillips'),
VALUES  ('lauralopez@hotmail.com', ' Laura Lopez'),
VALUES  ('lauralopez@hotmail.com', ' Laura Lopez'),
VALUES  ('suzannevasquez@example.net', ' Suzanne Vasquez'),
VALUES  ('suzannevasquez@example.net', ' Suzanne Vasquez'),
VALUES  ('kevinclements@hotmail.com', ' Kevin Clements'),
VALUES  ('kevinclements@hotmail.com', ' Kevin Clements'),
VALUES  ('kevinclements@hotmail.com', ' Kevin Clements'),
VALUES  ('erichernandez@gmail.com', ' Eric Hernandez'),
VALUES  ('erichernandez@gmail.com', ' Eric Hernandez'),
VALUES  ('dr.hannahwashington@gmail.com', ' Dr. Hannah Washington'),
VALUES  ('dr.hannahwashington@gmail.com', ' Dr. Hannah Washington'),
VALUES  ('dr.hannahwashington@gmail.com', ' Dr. Hannah Washington'),
VALUES  ('cindyrussell@example.net', ' Cindy Russell'),
VALUES  ('cindyrussell@example.net', ' Cindy Russell'),
VALUES  ('carmenstokes@example.net', ' Carmen Stokes'),
VALUES  ('carmenstokes@example.net', ' Carmen Stokes'),
VALUES  ('carmenstokes@example.net', ' Carmen Stokes'),
VALUES  ('lauraflynn@example.com', ' Laura Flynn'),
VALUES  ('lauraflynn@example.com', ' Laura Flynn'),
VALUES  ('lauraflynn@example.com', ' Laura Flynn'),
VALUES  ('nicholaswilliamsjr.@hotmail.com', ' Nicholas Williams Jr.'),
VALUES  ('nicholaswilliamsjr.@hotmail.com', ' Nicholas Williams Jr.'),
VALUES  ('sherrymills@hotmail.com', ' Sherry Mills'),
VALUES  ('sherrymills@hotmail.com', ' Sherry Mills'),
VALUES  ('lindamorris@example.com', ' Linda Morris'),
VALUES  ('lindamorris@example.com', ' Linda Morris'),
VALUES  ('jessemays@example.com', ' Jesse Mays'),
VALUES  ('jessemays@example.com', ' Jesse Mays'),
VALUES  ('jasonjuarez@hotmail.com', ' Jason Juarez'),
VALUES  ('jasonjuarez@hotmail.com', ' Jason Juarez'),
VALUES  ('lauraprice@example.net', ' Laura Price'),
VALUES  ('lauraprice@example.net', ' Laura Price'),
VALUES  ('patriciarichardson@example.com', ' Patricia Richardson'),
VALUES  ('patriciarichardson@example.com', ' Patricia Richardson'),
VALUES  ('williamtaylor@example.net', ' William Taylor'),
VALUES  ('williamtaylor@example.net', ' William Taylor'),
VALUES  ('williamtaylor@example.net', ' William Taylor'),
VALUES  ('matthewbryan@example.net', ' Matthew Bryan'),
VALUES  ('matthewbryan@example.net', ' Matthew Bryan'),
VALUES  ('matthewbryan@example.net', ' Matthew Bryan'),
VALUES  ('lisagreen@gmail.com', ' Lisa Green'),
VALUES  ('lisagreen@gmail.com', ' Lisa Green'),
VALUES  ('kristenwatsondds@example.com', ' Kristen Watson DDS'),
VALUES  ('kristenwatsondds@example.com', ' Kristen Watson DDS'),
VALUES  ('kristenwatsondds@example.com', ' Kristen Watson DDS'),
VALUES  ('rebeccabowman@hotmail.com', ' Rebecca Bowman'),
VALUES  ('rebeccabowman@hotmail.com', ' Rebecca Bowman'),
VALUES  ('rebeccabowman@hotmail.com', ' Rebecca Bowman'),
VALUES  ('mr.connorpugh@example.com', ' Mr. Connor Pugh'),
VALUES  ('wesleymiranda@example.net', ' Wesley Miranda'),
VALUES  ('davidscott@hotmail.com', ' David Scott'),
VALUES  ('davidscott@hotmail.com', ' David Scott'),
VALUES  ('courtneyanderson@example.net', ' Courtney Anderson'),
VALUES  ('courtneyanderson@example.net', ' Courtney Anderson'),
VALUES  ('juliesummers@example.com', ' Julie Summers'),
VALUES  ('juliesummers@example.com', ' Julie Summers'),
VALUES  ('juliesummers@example.com', ' Julie Summers'),
VALUES  ('michaelgreen@example.com', ' Michael Green'),
VALUES  ('michaelgreen@example.com', ' Michael Green'),
VALUES  ('michaelgreen@example.com', ' Michael Green'),
VALUES  ('tracyphelps@hotmail.com', ' Tracy Phelps'),
VALUES  ('tracyphelps@hotmail.com', ' Tracy Phelps'),
VALUES  ('jeremytorres@gmail.com', ' Jeremy Torres'),
VALUES  ('vincentsantos@example.com', ' Vincent Santos'),
VALUES  ('vincentsantos@example.com', ' Vincent Santos'),
VALUES  ('dr.davidstevensdds@hotmail.com', ' Dr. David Stevens DDS'),
VALUES  ('dr.davidstevensdds@hotmail.com', ' Dr. David Stevens DDS'),
VALUES  ('amydominguez@hotmail.com', ' Amy Dominguez'),
VALUES  ('amydominguez@hotmail.com', ' Amy Dominguez'),
VALUES  ('cindymarsh@example.com', ' Cindy Marsh'),
VALUES  ('cindymarsh@example.com', ' Cindy Marsh'),
VALUES  ('cindymarsh@example.com', ' Cindy Marsh'),
VALUES  ('ivanrichardson@example.com', ' Ivan Richardson'),
VALUES  ('ivanrichardson@example.com', ' Ivan Richardson'),
VALUES  ('ivanrichardson@example.com', ' Ivan Richardson'),
VALUES  ('johnboyd@hotmail.com', ' John Boyd'),
VALUES  ('johnboyd@hotmail.com', ' John Boyd'),
VALUES  ('michaelbarnes@hotmail.com', ' Michael Barnes'),
VALUES  ('michaelbarnes@hotmail.com', ' Michael Barnes'),
VALUES  ('garyjackson@example.net', ' Gary Jackson'),
VALUES  ('garyjackson@example.net', ' Gary Jackson'),
VALUES  ('christopherflowers@hotmail.com', ' Christopher Flowers'),
VALUES  ('christopherflowers@hotmail.com', ' Christopher Flowers'),
VALUES  ('christopherflowers@hotmail.com', ' Christopher Flowers'),
VALUES  ('michaelthomas@example.net', ' Michael Thomas'),
VALUES  ('kylebrown@example.net', ' Kyle Brown'),
VALUES  ('kylebrown@example.net', ' Kyle Brown'),
VALUES  ('kylebrown@example.net', ' Kyle Brown'),
VALUES  ('sarahfischer@hotmail.com', ' Sarah Fischer'),
VALUES  ('sarahfischer@hotmail.com', ' Sarah Fischer'),
VALUES  ('sarahfischer@hotmail.com', ' Sarah Fischer'),
VALUES  ('ashleymorrison@example.com', ' Ashley Morrison'),
VALUES  ('ashleymorrison@example.com', ' Ashley Morrison'),
VALUES  ('ashleymorrison@example.com', ' Ashley Morrison'),
VALUES  ('kathymaldonado@example.com', ' Kathy Maldonado'),
VALUES  ('kathymaldonado@example.com', ' Kathy Maldonado'),
VALUES  ('karenmills@example.com', ' Karen Mills'),
VALUES  ('dr.jennifermorris@example.net', ' Dr. Jennifer Morris'),
VALUES  ('dr.jennifermorris@example.net', ' Dr. Jennifer Morris'),
VALUES  ('dr.jennifermorris@example.net', ' Dr. Jennifer Morris'),
VALUES  ('katherinepadilla@hotmail.com', ' Katherine Padilla'),
VALUES  ('katherinepadilla@hotmail.com', ' Katherine Padilla'),
VALUES  ('stephaniehampton@example.com', ' Stephanie Hampton'),
VALUES  ('stephaniehampton@example.com', ' Stephanie Hampton'),
VALUES  ('stephaniehampton@example.com', ' Stephanie Hampton'),
VALUES  ('cherylharper@gmail.com', ' Cheryl Harper'),
VALUES  ('cherylharper@gmail.com', ' Cheryl Harper'),
VALUES  ('valeriewilson@hotmail.com', ' Valerie Wilson'),
VALUES  ('valeriewilson@hotmail.com', ' Valerie Wilson'),
VALUES  ('troybrown@example.com', ' Troy Brown'),
VALUES  ('troybrown@example.com', ' Troy Brown'),
VALUES  ('antoniohorn@example.net', ' Antonio Horn'),
VALUES  ('antoniohorn@example.net', ' Antonio Horn'),
VALUES  ('antoniohorn@example.net', ' Antonio Horn'),
VALUES  ('curtissingleton@example.net', ' Curtis Singleton'),
VALUES  ('curtissingleton@example.net', ' Curtis Singleton'),
VALUES  ('joannbarnett@example.net', ' Joann Barnett'),
VALUES  ('joannbarnett@example.net', ' Joann Barnett'),
VALUES  ('maxsmith@example.com', ' Max Smith'),
VALUES  ('maxsmith@example.com', ' Max Smith'),
VALUES  ('lesliebuchanan@gmail.com', ' Leslie Buchanan'),
VALUES  ('lesliebuchanan@gmail.com', ' Leslie Buchanan'),
VALUES  ('lesliebuchanan@gmail.com', ' Leslie Buchanan'),
VALUES  ('josephgomez@example.com', ' Joseph Gomez'),
VALUES  ('josephgomez@example.com', ' Joseph Gomez'),
VALUES  ('johnharris@example.com', ' John Harris'),
VALUES  ('johnharris@example.com', ' John Harris'),
VALUES  ('johnharris@example.com', ' John Harris'),
VALUES  ('peterallen@hotmail.com', ' Peter Allen'),
VALUES  ('peterallen@hotmail.com', ' Peter Allen'),
VALUES  ('jeffreyshelton@example.com', ' Jeffrey Shelton'),
VALUES  ('jeffreyshelton@example.com', ' Jeffrey Shelton'),
VALUES  ('jeffreyshelton@example.com', ' Jeffrey Shelton'),
VALUES  ('jamiewoods@example.net', ' Jamie Woods'),
VALUES  ('jamiewoods@example.net', ' Jamie Woods'),
VALUES  ('michellepeck@gmail.com', ' Michelle Peck'),
VALUES  ('michellepeck@gmail.com', ' Michelle Peck'),
VALUES  ('annahenderson@example.net', ' Anna Henderson'),
VALUES  ('annahenderson@example.net', ' Anna Henderson'),
VALUES  ('saraford@example.com', ' Sara Ford'),
VALUES  ('saraford@example.com', ' Sara Ford'),
VALUES  ('annwhite@example.com', ' Ann White'),
VALUES  ('annwhite@example.com', ' Ann White'),
VALUES  ('andrewortiz@gmail.com', ' Andrew Ortiz'),
VALUES  ('andrewortiz@gmail.com', ' Andrew Ortiz'),
VALUES  ('andrewortiz@gmail.com', ' Andrew Ortiz'),
VALUES  ('jennifermay@example.net', ' Jennifer May'),
VALUES  ('rachaeltaylor@example.com', ' Rachael Taylor'),
VALUES  ('rachaeltaylor@example.com', ' Rachael Taylor'),
VALUES  ('timothystevens@example.net', ' Timothy Stevens'),
VALUES  ('timothystevens@example.net', ' Timothy Stevens'),
VALUES  ('timothystevens@example.net', ' Timothy Stevens'),
VALUES  ('derekturner@example.net', ' Derek Turner'),
VALUES  ('amywang@hotmail.com', ' Amy Wang'),
VALUES  ('amywang@hotmail.com', ' Amy Wang'),
INSERT INTO Institution ('name', 'country')
VALUES  (' Danielle Burgess', ' University of Greenland'),
VALUES  (' Danielle Burgess', ' Royal University of Bhutan'),
VALUES  (' Deanna Harris', ' Khulna University of Engineering And Technology'),
VALUES  (' Deanna Harris', ' European University Portugal'),
VALUES  (' Joseph Andrews', ' University of Swaziland'),
VALUES  (' Joseph Andrews', ' University of New Caledonia'),
VALUES  (' Greg Lopez', ' Tajik National University'),
VALUES  (' Greg Lopez', ' Yangtze Normal University'),
VALUES  (' Brian Sloan', ' Algebra University College'),
VALUES  (' Brian Sloan', ' University for Development Studies'),
VALUES  (' Nancy Alexander', ' University of Western Sydney'),
VALUES  (' Nancy Alexander', ' American University of Science and Technology'),
VALUES  (' Nancy Alexander', ' American University of Antigua'),
VALUES  (' Daniel Lopez', ' Singapore Management University'),
VALUES  (' Daniel Lopez', ' Hope Africa University'),
VALUES  (' Daniel Lopez', ' European University Portugal'),
VALUES  (' Mrs. Leslie Lane', " St. George's University"),
VALUES  (' Mrs. Leslie Lane', ' University of Venice'),
VALUES  (' Mrs. Leslie Lane', ' Cyprus International University'),
VALUES  (' Anthony Myers', ' National University of Samoa'),
VALUES  (' Anthony Myers', ' International University Institute of Luxembourg'),
VALUES  (' Stephen Burnett', ' Tajikistan International University'),
VALUES  (' Stephen Burnett', ' Technological University (Taunggyi)'),
VALUES  (' Stephen Burnett', ' Alahgaff University'),
VALUES  (' Sara Mcdonald', ' Xiangtan Normal University'),
VALUES  (' John Morris', ' St. Matthews University'),
VALUES  (' John Morris', ' University of Johannesburg'),
VALUES  (' Peter Williams', ' University of Greenland'),
VALUES  (' Michael Trujillo', ' Jumeira University'),
VALUES  (' Michael Trujillo', ' University of Namibia'),
VALUES  (' Scott Lara', ' University of Swaziland'),
VALUES  (' Scott Lara', ' Law University of Bratislava'),
VALUES  (' Eric Burgess', ' Prince Sultan University'),
VALUES  (' Eric Burgess', ' American University of the Caribbean'),
VALUES  (' Jessica Ponce', ' Kanto Gakuin University'),
VALUES  (' Jessica Ponce', ' Kigali Independent University'),
VALUES  (' Mr. Michael Keith DDS', ' Al Imam Al-Ouzai University'),
VALUES  (' Mr. Michael Keith DDS', ' Royal University of Bhutan'),
VALUES  (' Joseph Glass', ' Al Akhawayn University'),
VALUES  (' Joseph Glass', ' Odense University'),
VALUES  (' Christopher Galvan', ' EUCLID University'),
VALUES  (' Christopher Galvan', ' Grand Canyon University'),
VALUES  (' Christopher Galvan', ' University of Saint Joseph'),
VALUES  (' Gregory Brock', ' Rusangu University'),
VALUES  (' Justin Grant Jr.', ' University of Macau'),
VALUES  (' Justin Grant Jr.', ' American University of the Caribbean'),
VALUES  (' Rose Ryan', ' Sun Yat-Sen University of Medical Sciences'),
VALUES  (' Rose Ryan', ' Technical University of Zielona Gora'),
VALUES  (' Rose Ryan', ' University of Aviation and Technology'),
VALUES  (' Stephanie Preston', ' University of Sopron'),
VALUES  (' Stephanie Preston', ' International Sakharov Environmental University'),
VALUES  (' Stephanie Preston', ' Royal University of Bhutan'),
VALUES  (' Michael Velasquez', ' Ilia Chavchavadze State University'),
VALUES  (' Michael Velasquez', " St. George's University"),
VALUES  (' Daniel Frey', ' National University of Ireland'),
VALUES  (' Daniel Frey', ' Southern Arkansas University Tech'),
VALUES  (' Karen Mueller', ' Nakhchivan State University'),
VALUES  (' Karen Mueller', ' American University of Middle East'),
VALUES  (' Karen Mueller', ' Siauliai University'),
VALUES  (' Elizabeth Hartman', ' Latvia University of Life Sciences and Technologies'),
VALUES  (' Philip Luna', ' University of Latvia'),
VALUES  (' Philip Luna', ' Pamir University'),
VALUES  (' Philip Luna', ' Tbilisi State University'),
VALUES  (' Timothy Nelson', ' Hadhramout University of Science and Technology'),
VALUES  (' Timothy Nelson', ' National University of Rwanda'),
VALUES  (' Timothy Nelson', ' Espam Formation University'),
VALUES  (' Jeremy Smith', ' University of the Faroe Islands'),
VALUES  (' Jeremy Smith', " St. George's University"),
VALUES  (' Jeremy Smith', ' Arab European University'),
VALUES  (' Barbara Smith', ' Hope Africa University'),
VALUES  (' Barbara Smith', ' American University of Paris'),
VALUES  (' David Hodge', ' Singidunum University'),
VALUES  (' David Hodge', ' Shomal University'),
VALUES  (' Timothy Williamson', ' Czech Technical University of Prague'),
VALUES  (' Timothy Williamson', ' Toyo Gakuen University'),
VALUES  (' Ralph Jackson', ' Victoria University'),
VALUES  (' Ralph Jackson', ' International Turkmen Turkish University'),
VALUES  (' Taylor Ryan', ' Kandahar University'),
VALUES  (' Taylor Ryan', ' Tbilisi State Medical University'),
VALUES  (' Travis Thomas', ' Lebanese University'),
VALUES  (' Travis Thomas', ' Texila American University'),
VALUES  (' Leah Phelps', ' University College of Kristianstad'),
VALUES  (' Leah Phelps', ' European University Portugal'),
VALUES  (' Leah Phelps', ' University of Fiji'),
VALUES  (' Ruben Hubbard', ' Ama International University'),
VALUES  (' Ruben Hubbard', ' Future University'),
VALUES  (' Samantha Sullivan', ' University of the South Pacific'),
VALUES  (' Samantha Sullivan', ' University of Luxemburg'),
VALUES  (' Erika Campbell', ' Chongqing Technology and Business University'),
VALUES  (' Erika Campbell', ' St. Matthews University'),
VALUES  (' Erika Campbell', ' Swiss German University'),
VALUES  (' Danielle Gentry', ' University for Peace'),
VALUES  (' Danielle Gentry', ' Westhill University'),
VALUES  (' Danielle Gentry', ' Buddhasravaka Bhikshu University'),
VALUES  (' Edward Roberts', ' University of Aviation and Technology'),
VALUES  (' Edward Roberts', ' University of Seychelles'),
VALUES  (' Edward Roberts', ' Khazar University'),
VALUES  (' Jillian Ho', ' Northwestern University In Qatar'),
VALUES  (' Jillian Ho', ' Appalachian State University'),
VALUES  (' Jillian Ho', ' Frederick University'),
VALUES  (' Karen Miller', ' University of Namibia'),
VALUES  (' Karen Miller', ' American University of Middle East'),
VALUES  (' Karen Miller', ' University of Akureyri'),
VALUES  (' Gabriel Larson', ' University of Southern Europe (Monaco Business School)'),
VALUES  (' Gabriel Larson', ' University of Montenegro'),
VALUES  (' Nicole Holland', ' Pacific Adventist University'),
VALUES  (' Nicole Holland', ' Chaudhary Charan Singh Haryana Agricultural University'),
VALUES  (' Nicole Holland', ' University of the Faroe Islands'),
VALUES  (' Allison Cross', ' University of Technology'),
VALUES  (' Allison Cross', ' Tbilisi Pedagogical University'),
VALUES  (' Laura Jones', ' Tbilisi State Medical University'),
VALUES  (' Laura Jones', ' Alhosn University'),
VALUES  (' Jody Parker', ' Nkumba University'),
VALUES  (' Jody Parker', ' Military University Shoumen'),
VALUES  (' Michelle Anthony', ' Dimocritus University of Thrace'),
VALUES  (' Michelle Anthony', ' National University of Lesotho'),
VALUES  (' Michelle Anthony', ' American University of the Caribbean'),
VALUES  (' Kevin Tanner', ' Don Mariano Marcos Memorial State University'),
VALUES  (' Adam Williams', ' University of Zurich'),
VALUES  (' Adam Williams', ' University for Peace'),
VALUES  (' Jessica Callahan', ' Shih Chien University'),
VALUES  (' Jessica Callahan', ' European Humanities University'),
VALUES  (' Tiffany Martinez', ' University of Aviation and Technology'),
VALUES  (' Tiffany Martinez', ' University of Haifa'),
VALUES  (' Amanda Andrews', ' Jumeira University'),
VALUES  (' Amanda Andrews', ' Maldives National University'),
VALUES  (' James Medina', ' University of Novi Sad'),
VALUES  (' James Medina', ' Pavol Jozef Safarik University in Kosice'),
VALUES  (' James Medina', ' University of Andorra'),
VALUES  (' Vanessa Green', ' Technical University in Kosice'),
VALUES  (' Vanessa Green', ' Daugavpils University'),
VALUES  (' Vanessa Green', ' Dutch Delta University'),
VALUES  (' Anthony Brewer', ' Anton de Kom University'),
VALUES  (' Melissa Ortega', ' St Clements University - Higher Education School'),
VALUES  (' Melissa Ortega', ' Caribbean University'),
VALUES  (' Melissa Ortega', ' Maakhir University'),
VALUES  (' William Shepard', ' West Coast University (WCU)'),
VALUES  (' William Shepard', ' Espam Formation University'),
VALUES  (' William Shepard', ' Maldives National University'),
VALUES  (' Laura Pace', ' University of Qatar'),
VALUES  (' Laura Pace', ' University of Swaziland'),
VALUES  (' Laura Pace', ' University of Tromsø'),
VALUES  (' Stephanie Bean', ' National University of Samoa'),
VALUES  (' Stephanie Bean', ' Prince Sultan University'),
VALUES  (' Troy Bush', ' Agder University College'),
VALUES  (' Troy Bush', ' Helwan University'),
VALUES  (' Troy Bush', ' University for Peace'),
VALUES  (' Carol Haynes', ' American University In Kosovo'),
VALUES  (' Carol Haynes', ' University for Peace'),
VALUES  (' Angel Shelton', ' University of Mauritius'),
VALUES  (' Angel Shelton', ' University of Venda'),
VALUES  (' Angel Shelton', ' Houdegbe North American University Benin'),
VALUES  (' Taylor Graham', ' University of Technology Jamaica'),
VALUES  (' Taylor Graham', ' Royal University of Bhutan'),
VALUES  (' Taylor Graham', ' Kyrgyz Turkish  Manas University'),
VALUES  (' Patricia Riley', ' Walailak University'),
VALUES  (' Patricia Riley', ' University of Gjirokstra "Eqerem Cabej"'),
VALUES  (' Patricia Riley', ' Silliman University'),
VALUES  (' Manuel Serrano', ' University “Pavaresia” Vlore'),
VALUES  (' Nicole Lane', ' Bircham International University'),
VALUES  (' Nicole Lane', ' University of Applied Sciences Aargau'),
VALUES  (' Colleen Aguilar', ' University of Andorra'),
VALUES  (' Colleen Aguilar', ' University of Nova Gorica'),
VALUES  (' Colleen Aguilar', ' Tbilisi State Medical University'),
VALUES  (' Heather Cordova', ' Soochow University'),
VALUES  (' Heather Cordova', ' Al-Isra University'),
VALUES  (' Mrs. Danielle Young', ' Binus University'),
VALUES  (' Mrs. Danielle Young', ' Espam Formation University'),
VALUES  (' Derek Harrell', ' Diaconia University of Applied Sciences'),
VALUES  (' Derek Harrell', ' University of Indianapolis in Athens'),
VALUES  (' Dennis Mcdaniel', ' University of the South Pacific School of Agriculture'),
VALUES  (' Dennis Mcdaniel', ' Qom University of Medical Sciences'),
VALUES  (' Dennis Mcdaniel', ' 2nd Military Medical University'),
VALUES  (' David Thornton', ' Girne American University'),
VALUES  (' David Thornton', ' Anton de Kom University'),
VALUES  (' Craig Robinson', ' Technological University (Myitkyina)'),
VALUES  (' Craig Robinson', ' National Taipei University of Technology'),
VALUES  (' Timothy Martin', ' Caribbean University'),
VALUES  (' Kevin Williams', ' Al Akhawayn University'),
VALUES  (' Kevin Williams', ' Floret Global University'),
VALUES  (' Derek Richardson', ' Bamenda University of Science & Technology'),
VALUES  (' Cody Nguyen', ' National Technical University of Athens'),
VALUES  (' Cody Nguyen', ' Gulf University for Science and Technology'),
VALUES  (' Cody Nguyen', ' University of Southern Europe (Monaco Business School)'),
VALUES  (' Hannah Hall', ' State University of Tetova'),
VALUES  (' Hannah Hall', ' Al Mamon University College'),
VALUES  (' Hannah Hall', ' Armenian State University of Economics'),
VALUES  (' Crystal Kim', ' University of Southern Europe (Monaco Business School)'),
VALUES  (' Andrea Gilmore MD', ' University of Sarajevo'),
VALUES  (' Andrea Gilmore MD', ' Westhill University'),
VALUES  (' Elizabeth Hubbard', ' Belarussian State Medical University'),
VALUES  (' Elizabeth Hubbard', ' Technical University of Denmark'),
VALUES  (' Elizabeth Hubbard', ' Higher School of University and Advanced Studies Pisa'),
VALUES  (' Jennifer Wilkerson', ' Charisma University'),
VALUES  (' Jennifer Wilkerson', ' University of Guam'),
VALUES  (' Paula Shaffer', ' International University of Management'),
VALUES  (' Paula Shaffer', ' University of Saint Joseph'),
VALUES  (' Paula Shaffer', ' University of Liberia'),
VALUES  (' Kevin Holmes', ' Ross University Caribbean School of Veterinary Medicine'),
VALUES  (' Kevin Holmes', ' Technological University of Iceland'),
VALUES  (' Kevin Holmes', ' University of Montenegro'),
VALUES  (' Brandon Compton', ' Victoria University of Wellington'),
VALUES  (' Brandon Compton', ' Malawi University of Business and Applied Sciences'),
VALUES  (' Brandon Compton', ' Nigerian Turkish Nile University'),
VALUES  (' Ariana Greer', ' Saba University'),
VALUES  (' Ariana Greer', ' Durban University of Technology'),
VALUES  (' Ariana Greer', ' Bar-Ilan University'),
VALUES  (' Kimberly Patton', ' Al Akhawayn University'),
VALUES  (' Kimberly Patton', ' University of Juba'),
VALUES  (' Beth Manning', ' Gemsville Technical University'),
VALUES  (' Beth Manning', ' University of Namibia'),
VALUES  (' Ruben Robbins', ' European University Portugal'),
VALUES  (' Ruben Robbins', " St Theresa's Medical University"),
VALUES  (' Kelly Davis', ' Kar University'),
VALUES  (' Kelly Davis', ' University of Auckland'),
VALUES  (' Joel Smith', ' University of Andorra'),
VALUES  (' Joel Smith', ' University of Montenegro'),
VALUES  (' Stacey Pearson', ' Midlands State University'),
VALUES  (' Stacey Pearson', ' Bingol University'),
VALUES  (' Billy Salas DVM', ' Nevsehir Haci Bektas Veli University'),
VALUES  (' Billy Salas DVM', ' Benadir University'),
VALUES  (' David Sampson', ' European Carolus Magnus University'),
VALUES  (' David Sampson', ' ABM University College'),
VALUES  (' Emma Solomon', ' University of Korca "Fan Noli"'),
VALUES  (' Emma Solomon', ' National University of Laos'),
VALUES  (' Emma Solomon', ' HTW Chur - University of Applied Sciences HTW Chur'),
VALUES  (' Leslie Madden', ' Petrozavodsk State University'),
VALUES  (' Leslie Madden', ' University Marien Ngouabi Brazzaville'),
VALUES  (' Leslie Madden', ' Victoria University'),
VALUES  (' Kyle Bates', ' Purbanchal University'),
VALUES  (' Kyle Bates', ' University of the Faroe Islands'),
VALUES  (' Carly Turner', ' Australian National University'),
VALUES  (' Carly Turner', ' Al-Asmarya University for Islamic Studies'),
VALUES  (' Sophia Holden', ' National University of Rwanda'),
VALUES  (' Sophia Holden', ' Chinese University of Hong Kong'),
VALUES  (' Parker Buckley', ' Royal University of Fine Arts'),
VALUES  (' Parker Buckley', ' Harvard University'),
VALUES  (' James Young', ' University of the South Pacific'),
VALUES  (' Douglas Case', ' University of Pardubice'),
VALUES  (' Douglas Case', ' Papua New Guinea University of Technology'),
VALUES  (' Peggy Hess', ' Al Mamon University College'),
VALUES  (' Peggy Hess', ' University of Newcastle'),
VALUES  (' Peggy Hess', ' Singapore Management University'),
VALUES  (' Francis Wilson', ' St Clements University - Higher Education School'),
VALUES  (' Francis Wilson', ' University of the Faroe Islands'),
VALUES  (' Jennifer Brown', ' Kigali Independent University'),
VALUES  (' Jennifer Brown', ' University of Seychelles'),
VALUES  (' Jennifer Brown', ' Dhofar University'),
VALUES  (' Lisa Barnes', ' Lampang Rajabhat University'),
VALUES  (' Danielle Chavez', ' Hong Kong Baptist University'),
VALUES  (' Danielle Chavez', ' State University of Tetova'),
VALUES  (' Danielle Chavez', ' Pacific Adventist University'),
VALUES  (' Eduardo Burns', ' National University of Lesotho'),
VALUES  (' Eduardo Burns', ' Technological University (Kyaukse)'),
VALUES  (' Troy Morrison', ' University Marien Ngouabi Brazzaville'),
VALUES  (' Troy Morrison', ' Northern Caribbean University'),
VALUES  (' Scott Miller', ' Zimbabwe Open University'),
VALUES  (' Scott Miller', ' Northern Caribbean University'),
VALUES  (' Cynthia Bailey', ' Duta Bangsa University'),
VALUES  (' Cynthia Bailey', ' University of Health Sciences Antigua'),
VALUES  (' Cynthia Bailey', ' New World University'),
VALUES  (' Jack Williams', ' Kotelawala Defence University'),
VALUES  (' Jack Williams', ' Bamenda University of Science & Technology'),
VALUES  (' Jack Williams', ' Fiji National University'),
VALUES  (' Oscar Cole', ' University of Brunei Darussalam'),
VALUES  (' Oscar Cole', ' University of the South Pacific'),
VALUES  (' Jonathan Taylor', ' Trinity University School of Medicine'),
VALUES  (' Jonathan Taylor', ' University of Andorra'),
VALUES  (' Tracy Rodriguez', ' American University In Kosovo'),
VALUES  (' Tracy Rodriguez', ' Catholic University of Malawi'),
VALUES  (' Tracy Rodriguez', ' Gomel State Medical University'),
VALUES  (' James Williams', ' Aletheia University'),
VALUES  (' James Williams', ' Swiss German University'),
VALUES  (' Thomas Fisher', ' National University of Rwanda'),
VALUES  (' Thomas Fisher', ' Hatyai University'),
VALUES  (' Ashley Sims', ' Royal University of Bhutan'),
VALUES  (' Ashley Sims', ' Medical University Pleven'),
VALUES  (' Todd Davis', ' Southern University and A&M College'),
VALUES  (' Todd Davis', ' Law University of Bratislava'),
VALUES  (' Tanya Garcia', ' Trinity University School of Medicine'),
VALUES  (' Tanya Garcia', ' University of Andorra'),
VALUES  (' Sara Woods', ' American University of the Caribbean'),
VALUES  (' Sara Woods', ' Herat University'),
VALUES  (' Sara Woods', ' Caribbean University'),
VALUES  (' Michele Rice', ' University of the South Pacific Centre'),
VALUES  (' Michele Rice', ' Kigali Independent University'),
VALUES  (' Tina Moore', ' International Blacksea University'),
VALUES  (' Tina Moore', ' Lappeenranta University of Technology'),
VALUES  (' Tina Moore', ' Bamenda University of Science & Technology'),
VALUES  (' Johnny Grant', ' University of Northern Bahr El-Ghazal'),
VALUES  (' Johnny Grant', ' European University'),
VALUES  (' Adam Peterson', ' Purdue University Fort Wayne'),
VALUES  (' Adam Peterson', ' State University of Tetova'),
VALUES  (' Katherine Mendez', ' Donetsk National Technical University'),
VALUES  (' Katherine Mendez', ' University Marien Ngouabi Brazzaville'),
VALUES  (' Jason Phillips', ' University of the Southern Caribbean'),
VALUES  (' Jason Phillips', ' University of Pannonia'),
VALUES  (' Laura Lopez', ' University for Peace'),
VALUES  (' Laura Lopez', ' Jordan University of Science and Technology'),
VALUES  (' Suzanne Vasquez', ' Sirte University'),
VALUES  (' Suzanne Vasquez', ' American University of Antigua'),
VALUES  (' Kevin Clements', ' Charisma University'),
VALUES  (' Kevin Clements', ' National University of Samoa'),
VALUES  (' Kevin Clements', ' Yanbu University College'),
VALUES  (' Eric Hernandez', ' University of Cassino'),
VALUES  (' Eric Hernandez', ' University of SS. Cyril and Methodius in Trnava'),
VALUES  (' Dr. Hannah Washington', ' National University of Lesotho'),
VALUES  (' Dr. Hannah Washington', ' University Marien Ngouabi Brazzaville'),
VALUES  (' Dr. Hannah Washington', ' University Medical School of Debrecen'),
VALUES  (' Cindy Russell', ' International University Institute of Luxembourg'),
VALUES  (' Cindy Russell', ' Singapore Management University'),
VALUES  (' Carmen Stokes', ' Biju Pattnaik University of Technology'),
VALUES  (' Carmen Stokes', ' Crawford University'),
VALUES  (' Carmen Stokes', ' University of Northern Bahr El-Ghazal'),
VALUES  (' Laura Flynn', ' Sefako Makgatho Health Sciences University'),
VALUES  (' Laura Flynn', ' Chulalongkorn University'),
VALUES  (' Laura Flynn', ' European University Portugal'),
VALUES  (' Nicholas Williams Jr.', ' Uzima University College'),
VALUES  (' Nicholas Williams Jr.', ' University of Namibia'),
VALUES  (' Sherry Mills', ' Sur University College'),
VALUES  (' Sherry Mills', " Norway's Information Technology University College"),
VALUES  (' Linda Morris', ' Suez Canal University'),
VALUES  (' Linda Morris', ' Australian National University'),
VALUES  (' Jesse Mays', ' Zurich University of Applied Sciences Winterthur'),
VALUES  (' Jesse Mays', ' University of Mauritius'),
VALUES  (' Jason Juarez', ' Saba University'),
VALUES  (' Jason Juarez', ' University of the Faroe Islands'),
VALUES  (' Laura Price', ' Arab Open University'),
VALUES  (' Laura Price', ' University of Kuopio'),
VALUES  (' Patricia Richardson', ' West Coast University (WCU)'),
VALUES  (' Patricia Richardson', ' Bamenda University of Science & Technology'),
VALUES  (' William Taylor', ' University of Zambia'),
VALUES  (' William Taylor', ' Tajik Agrarian University'),
VALUES  (' William Taylor', ' University of Basel'),
VALUES  (' Matthew Bryan', ' Tajik National University'),
VALUES  (' Matthew Bryan', ' University of the West Indies St. Augustine'),
VALUES  (' Matthew Bryan', ' Hsuan Chuang University'),
VALUES  (' Lisa Green', ' Omdurman Islamic University'),
VALUES  (' Lisa Green', ' Eurasia International University'),
VALUES  (' Kristen Watson DDS', ' Central University College'),
VALUES  (' Kristen Watson DDS', ' Sol Plaatje University'),
VALUES  (' Kristen Watson DDS', ' Diaconia University of Applied Sciences'),
VALUES  (' Rebecca Bowman', ' University of Aviation and Technology'),
VALUES  (' Rebecca Bowman', ' Royal University of Bhutan'),
VALUES  (' Rebecca Bowman', ' Botswana International University of Science & Technology'),
VALUES  (' Mr. Connor Pugh', ' Hue University of Agriculture and Forestry'),
VALUES  (' Wesley Miranda', ' The Education University of Hong Kong'),
VALUES  (' David Scott', ' Isra University'),
VALUES  (' David Scott', ' Technological University (Pinlon)'),
VALUES  (' Courtney Anderson', ' American University of the Caribbean'),
VALUES  (' Courtney Anderson', ' Paktia University'),
VALUES  (' Julie Summers', ' University of Ljubljana'),
VALUES  (' Julie Summers', ' Caribbean University'),
VALUES  (' Julie Summers', ' Lampang Rajabhat University'),
VALUES  (' Michael Green', ' Westhill University'),
VALUES  (' Michael Green', ' Hope Africa University'),
VALUES  (' Michael Green', ' Georgia Southwestern State University'),
VALUES  (' Tracy Phelps', ' University College Cork'),
VALUES  (' Tracy Phelps', ' Maldives National University'),
VALUES  (' Jeremy Torres', ' Hanoi University of Science and Technology'),
VALUES  (' Vincent Santos', ' European University Cyprus'),
VALUES  (' Vincent Santos', ' University of the Southern Caribbean'),
VALUES  (' Dr. David Stevens DDS', ' University of Bristol'),
VALUES  (' Dr. David Stevens DDS', ' University for Peace'),
VALUES  (' Amy Dominguez', ' Antalya international University'),
VALUES  (' Amy Dominguez', ' American University of Antigua'),
VALUES  (' Cindy Marsh', ' University of Greenland'),
VALUES  (' Cindy Marsh', ' Norton University'),
VALUES  (' Cindy Marsh', ' University of Brunei Darussalam'),
VALUES  (' Ivan Richardson', ' Northwestern University In Qatar'),
VALUES  (' Ivan Richardson', ' University of Food Technology'),
VALUES  (' Ivan Richardson', ' Trinity University School of Medicine'),
VALUES  (' John Boyd', ' University of Swaziland'),
VALUES  (' John Boyd', ' Nilai University College'),
VALUES  (' Michael Barnes', ' Anglo-American University'),
VALUES  (' Michael Barnes', ' Meiji Gakuin University'),
VALUES  (' Gary Jackson', ' University of Liberia'),
VALUES  (' Gary Jackson', ' Lilongwe University of Agriculture and Natural Resources'),
VALUES  (' Christopher Flowers', ' Zimbabwe Ezekiel Guti University'),
VALUES  (' Christopher Flowers', ' Westhill University'),
VALUES  (' Christopher Flowers', ' Texila American University'),
VALUES  (' Michael Thomas', ' Dedan Kimathi University of Technology'),
VALUES  (' Kyle Brown', ' University of Northern Bahr El-Ghazal'),
VALUES  (' Kyle Brown', ' University of Brunei Darussalam'),
VALUES  (' Kyle Brown', ' University of Saint Joseph'),
VALUES  (' Sarah Fischer', ' University of Swaziland'),
VALUES  (' Sarah Fischer', ' University of the Humanities'),
VALUES  (' Sarah Fischer', ' American University In Kosovo'),
VALUES  (' Ashley Morrison', ' King Saud bin Abdulaziz University for Health Sciences'),
VALUES  (' Ashley Morrison', ' American University In Kosovo'),
VALUES  (' Ashley Morrison', ' Spartan University of Health Sciences'),
VALUES  (' Kathy Maldonado', ' University of Akureyri'),
VALUES  (' Kathy Maldonado', ' Kigali Independent University'),
VALUES  (' Karen Mills', ' St Clements University - Higher Education School'),
VALUES  (' Dr. Jennifer Morris', ' Amman Arab University for Higher Studies'),
VALUES  (' Dr. Jennifer Morris', ' Royal University of Bhutan'),
VALUES  (' Dr. Jennifer Morris', ' The Hang Seng University of Hong Kong'),
VALUES  (' Katherine Padilla', " St. Mary's University"),
VALUES  (' Katherine Padilla', ' University of Malta'),
VALUES  (' Stephanie Hampton', ' The Kingdom University'),
VALUES  (' Stephanie Hampton', ' University of Oslo'),
VALUES  (' Stephanie Hampton', ' Anton de Kom University'),
VALUES  (' Cheryl Harper', ' University of the South Pacific'),
VALUES  (' Cheryl Harper', ' Hebei University'),
VALUES  (' Valerie Wilson', ' Vidzeme University College'),
VALUES  (' Valerie Wilson', ' Punjabi University Patiala'),
VALUES  (' Troy Brown', ' University of Malawi | Old'),
VALUES  (' Troy Brown', ' Zawiya University'),
VALUES  (' Antonio Horn', ' University of Aviation and Technology'),
VALUES  (' Antonio Horn', ' Espam Formation University'),
VALUES  (' Antonio Horn', ' Azerbaijan State Pedagogic University'),
VALUES  (' Curtis Singleton', ' Mount Saint Vincent University'),
VALUES  (' Curtis Singleton', ' Kyrgyz National Agrarian University'),
VALUES  (' Joann Barnett', ' University of Nizwa'),
VALUES  (' Joann Barnett', ' Gulf University for Science and Technology'),
VALUES  (' Max Smith', ' American University of Kuwait'),
VALUES  (' Max Smith', ' Kure University'),
VALUES  (' Leslie Buchanan', ' University of Pula'),
VALUES  (' Leslie Buchanan', ' National Taipei University'),
VALUES  (' Leslie Buchanan', ' University of the Faroe Islands'),
VALUES  (' Joseph Gomez', ' Leiden University'),
VALUES  (' Joseph Gomez', ' Binus University'),
VALUES  (' John Harris', ' Adventist University of Central Africa'),
VALUES  (' John Harris', ' Masinde Muliro University of Science and Technology'),
VALUES  (' John Harris', ' Metropolitan University'),
VALUES  (' Peter Allen', ' Uva Wellassa University'),
VALUES  (' Peter Allen', ' Azerbaijan University of Architecture and Construction'),
VALUES  (' Jeffrey Shelton', ' University of Reggio Calabria'),
VALUES  (' Jeffrey Shelton', ' University of the South Pacific'),
VALUES  (' Jeffrey Shelton', ' University of Rijeka'),
VALUES  (' Jamie Woods', ' Tajik Agrarian University'),
VALUES  (' Jamie Woods', ' Latvia University of Life Sciences and Technologies'),
VALUES  (' Michelle Peck', ' University of Mustansiriyah'),
VALUES  (' Michelle Peck', ' University of Technology'),
VALUES  (' Anna Henderson', ' Takhar University'),
VALUES  (' Anna Henderson', ' University of the Faroe Islands'),
VALUES  (' Sara Ford', ' Caribbean University'),
VALUES  (' Sara Ford', ' Mountains of the Moon University'),
VALUES  (' Ann White', ' Gemsville Technical University'),
VALUES  (' Ann White', ' University of Macau'),
VALUES  (' Andrew Ortiz', ' Sohar University'),
VALUES  (' Andrew Ortiz', ' Palacký University Olomouc'),
VALUES  (' Andrew Ortiz', ' American University of the Caribbean'),
VALUES  (' Jennifer May', ' Comenius University in Bratislava'),
VALUES  (' Rachael Taylor', ' University of Dubrovnik'),
VALUES  (' Rachael Taylor', ' University of the South Pacific Centre'),
VALUES  (' Timothy Stevens', ' Valahia University of Targoviste'),
VALUES  (' Timothy Stevens', ' Jerash Private University'),
VALUES  (' Timothy Stevens', ' University of Qatar'),
VALUES  (' Derek Turner', ' Al Akhawayn University'),
VALUES  (' Amy Wang', " St. George's University"),
VALUES  (' Amy Wang', ' University of Botswana'),
INSERT INTO Attended ('email', 'school_name', 'country', 'degree')
VALUES  ('danielleburgess@gmail.com', ' Greenland', ' University of Greenland', ' Bachelors'),
VALUES  ('danielleburgess@gmail.com', ' Bhutan', ' Royal University of Bhutan', ' Masters'),
VALUES  ('deannaharris@example.net', ' Bangladesh', ' Khulna University of Engineering And Technology', ' Bachelors'),
VALUES  ('deannaharris@example.net', ' Portugal', ' European University Portugal', ' Masters'),
VALUES  ('josephandrews@hotmail.com', ' Swaziland', ' University of Swaziland', ' Bachelors'),
VALUES  ('josephandrews@hotmail.com', ' New Caledonia', ' University of New Caledonia', ' Masters'),
VALUES  ('greglopez@example.com', ' Tajikistan', ' Tajik National University', ' Bachelors'),
VALUES  ('greglopez@example.com', ' China', ' Yangtze Normal University', ' Masters'),
VALUES  ('briansloan@example.com', ' Croatia', ' Algebra University College', ' Bachelors'),
VALUES  ('briansloan@example.com', ' Ghana', ' University for Development Studies', ' Masters'),
VALUES  ('nancyalexander@example.com', ' Australia', ' University of Western Sydney', ' Bachelors'),
VALUES  ('nancyalexander@example.com', ' Lebanon', ' American University of Science and Technology', ' Masters'),
VALUES  ('nancyalexander@example.com', ' Antigua and Barbuda', ' American University of Antigua', ' PhD'),
VALUES  ('daniellopez@hotmail.com', ' Singapore', ' Singapore Management University', ' Bachelors'),
VALUES  ('daniellopez@hotmail.com', ' Burundi', ' Hope Africa University', ' Masters'),
VALUES  ('daniellopez@hotmail.com', ' Portugal', ' European University Portugal', ' PhD'),
VALUES  ('mrs.leslielane@example.com', ' Grenada', " St. George's University", ' Bachelors'),
VALUES  ('mrs.leslielane@example.com', ' Italy', ' University of Venice', ' Masters'),
VALUES  ('mrs.leslielane@example.com', ' Cyprus', ' Cyprus International University', ' PhD'),
VALUES  ('anthonymyers@example.com', ' Samoa', ' National University of Samoa', ' Bachelors'),
VALUES  ('anthonymyers@example.com', ' Luxembourg', ' International University Institute of Luxembourg', ' PhD'),
VALUES  ('stephenburnett@gmail.com', ' Tajikistan', ' Tajikistan International University', ' Bachelors'),
VALUES  ('stephenburnett@gmail.com', ' Myanmar', ' Technological University (Taunggyi)', ' Masters'),
VALUES  ('stephenburnett@gmail.com', ' Yemen', ' Alahgaff University', ' PhD'),
VALUES  ('saramcdonald@hotmail.com', ' China', ' Xiangtan Normal University', ' Bachelors'),
VALUES  ('johnmorris@example.com', ' Cayman Islands', ' St. Matthews University', ' Bachelors'),
VALUES  ('johnmorris@example.com', ' South Africa', ' University of Johannesburg', ' Masters'),
VALUES  ('peterwilliams@gmail.com', ' Greenland', ' University of Greenland', ' Bachelors'),
VALUES  ('michaeltrujillo@hotmail.com', ' United Arab Emirates', ' Jumeira University', ' Bachelors'),
VALUES  ('michaeltrujillo@hotmail.com', ' Namibia', ' University of Namibia', ' Masters'),
VALUES  ('scottlara@example.com', ' Swaziland', ' University of Swaziland', ' Bachelors'),
VALUES  ('scottlara@example.com', ' Slovakia', ' Law University of Bratislava', ' Masters'),
VALUES  ('ericburgess@hotmail.com', ' Saudi Arabia', ' Prince Sultan University', ' Bachelors'),
VALUES  ('ericburgess@hotmail.com', ' Haiti', ' American University of the Caribbean', ' Masters'),
VALUES  ('jessicaponce@example.net', ' Japan', ' Kanto Gakuin University', ' Bachelors'),
VALUES  ('jessicaponce@example.net', ' Rwanda', ' Kigali Independent University', ' PhD'),
VALUES  ('mr.michaelkeithdds@example.com', ' Lebanon', ' Al Imam Al-Ouzai University', ' Masters'),
VALUES  ('mr.michaelkeithdds@example.com', ' Bhutan', ' Royal University of Bhutan', ' PhD'),
VALUES  ('josephglass@gmail.com', ' Morocco', ' Al Akhawayn University', ' Bachelors'),
VALUES  ('josephglass@gmail.com', ' Denmark', ' Odense University', ' Masters'),
VALUES  ('christophergalvan@example.net', ' Gambia', ' EUCLID University', ' Bachelors'),
VALUES  ('christophergalvan@example.net', ' United States', ' Grand Canyon University', ' Masters'),
VALUES  ('christophergalvan@example.net', ' Macao', ' University of Saint Joseph', ' PhD'),
VALUES  ('gregorybrock@example.net', ' Zambia', ' Rusangu University', ' Bachelors'),
VALUES  ('justingrantjr.@example.net', ' Macao', ' University of Macau', ' Bachelors'),
VALUES  ('justingrantjr.@example.net', ' Haiti', ' American University of the Caribbean', ' Masters'),
VALUES  ('roseryan@hotmail.com', ' China', ' Sun Yat-Sen University of Medical Sciences', ' Bachelors'),
VALUES  ('roseryan@hotmail.com', ' Poland', ' Technical University of Zielona Gora', ' Masters'),
VALUES  ('roseryan@hotmail.com', ' Tunisia', ' University of Aviation and Technology', ' PhD'),
VALUES  ('stephaniepreston@example.com', ' Hungary', ' University of Sopron', ' Bachelors'),
VALUES  ('stephaniepreston@example.com', ' Belarus', ' International Sakharov Environmental University', ' Masters'),
VALUES  ('stephaniepreston@example.com', ' Bhutan', ' Royal University of Bhutan', ' PhD'),
VALUES  ('michaelvelasquez@gmail.com', ' Georgia', ' Ilia Chavchavadze State University', ' Bachelors'),
VALUES  ('michaelvelasquez@gmail.com', ' Grenada', " St. George's University", ' Masters'),
VALUES  ('danielfrey@example.net', ' Ireland', ' National University of Ireland', ' Bachelors'),
VALUES  ('danielfrey@example.net', ' United States', ' Southern Arkansas University Tech', ' Masters'),
VALUES  ('karenmueller@example.net', ' Azerbaijan', ' Nakhchivan State University', ' Bachelors'),
VALUES  ('karenmueller@example.net', ' Kuwait', ' American University of Middle East', ' Masters'),
VALUES  ('karenmueller@example.net', ' Lithuania', ' Siauliai University', ' PhD'),
VALUES  ('elizabethhartman@example.com', ' Latvia', ' Latvia University of Life Sciences and Technologies', ' Masters'),
VALUES  ('philipluna@example.com', ' Latvia', ' University of Latvia', ' Bachelors'),
VALUES  ('philipluna@example.com', ' Afghanistan', ' Pamir University', ' Masters'),
VALUES  ('philipluna@example.com', ' Georgia', ' Tbilisi State University', ' PhD'),
VALUES  ('timothynelson@example.net', ' Yemen', ' Hadhramout University of Science and Technology', ' Bachelors'),
VALUES  ('timothynelson@example.net', ' Rwanda', ' National University of Rwanda', ' Masters'),
VALUES  ('timothynelson@example.net', ' Benin', ' Espam Formation University', ' PhD'),
VALUES  ('jeremysmith@example.net', ' Faroe Islands', ' University of the Faroe Islands', ' Bachelors'),
VALUES  ('jeremysmith@example.net', ' Grenada', " St. George's University", ' Masters'),
VALUES  ('jeremysmith@example.net', ' Syrian Arab Republic', ' Arab European University', ' PhD'),
VALUES  ('barbarasmith@example.com', ' Burundi', ' Hope Africa University', ' Bachelors'),
VALUES  ('barbarasmith@example.com', ' France', ' American University of Paris', ' Masters'),
VALUES  ('davidhodge@hotmail.com', ' Serbia', ' Singidunum University', ' Bachelors'),
VALUES  ('davidhodge@hotmail.com', ' Iran', ' Shomal University', ' Masters'),
VALUES  ('timothywilliamson@example.com', ' Czech Republic', ' Czech Technical University of Prague', ' Bachelors'),
VALUES  ('timothywilliamson@example.com', ' Japan', ' Toyo Gakuen University', ' Masters'),
VALUES  ('ralphjackson@hotmail.com', ' Switzerland', ' Victoria University', ' Bachelors'),
VALUES  ('ralphjackson@hotmail.com', ' Turkmenistan', ' International Turkmen Turkish University', ' Masters'),
VALUES  ('taylorryan@hotmail.com', ' Afghanistan', ' Kandahar University', ' Bachelors'),
VALUES  ('taylorryan@hotmail.com', ' Georgia', ' Tbilisi State Medical University', ' Masters'),
VALUES  ('travisthomas@hotmail.com', ' Lebanon', ' Lebanese University', ' Bachelors'),
VALUES  ('travisthomas@hotmail.com', ' Guyana', ' Texila American University', ' Masters'),
VALUES  ('leahphelps@example.com', ' Sweden', ' University College of Kristianstad', ' Bachelors'),
VALUES  ('leahphelps@example.com', ' Portugal', ' European University Portugal', ' Masters'),
VALUES  ('leahphelps@example.com', ' Fiji', ' University of Fiji', ' PhD'),
VALUES  ('rubenhubbard@example.com', ' Bahrain', ' Ama International University', ' Bachelors'),
VALUES  ('rubenhubbard@example.com', ' Egypt', ' Future University', ' PhD'),
VALUES  ('samanthasullivan@example.net', ' Solomon Islands', ' University of the South Pacific', ' Bachelors'),
VALUES  ('samanthasullivan@example.net', ' Luxembourg', ' University of Luxemburg', ' Masters'),
VALUES  ('erikacampbell@hotmail.com', ' China', ' Chongqing Technology and Business University', ' Bachelors'),
VALUES  ('erikacampbell@hotmail.com', ' Cayman Islands', ' St. Matthews University', ' Masters'),
VALUES  ('erikacampbell@hotmail.com', ' Indonesia', ' Swiss German University', ' PhD'),
VALUES  ('daniellegentry@example.net', ' Costa Rica', ' University for Peace', ' Bachelors'),
VALUES  ('daniellegentry@example.net', ' Mexico', ' Westhill University', ' Masters'),
VALUES  ('daniellegentry@example.net', ' Sri Lanka', ' Buddhasravaka Bhikshu University', ' PhD'),
VALUES  ('edwardroberts@example.net', ' Tunisia', ' University of Aviation and Technology', ' Bachelors'),
VALUES  ('edwardroberts@example.net', ' Seychelles', ' University of Seychelles', ' Masters'),
VALUES  ('edwardroberts@example.net', ' Azerbaijan', ' Khazar University', ' PhD'),
VALUES  ('jillianho@example.com', ' Qatar', ' Northwestern University In Qatar', ' Bachelors'),
VALUES  ('jillianho@example.com', ' United States', ' Appalachian State University', ' Masters'),
VALUES  ('jillianho@example.com', ' Cyprus', ' Frederick University', ' PhD'),
VALUES  ('karenmiller@example.net', ' Namibia', ' University of Namibia', ' Bachelors'),
VALUES  ('karenmiller@example.net', ' Kuwait', ' American University of Middle East', ' Masters'),
VALUES  ('karenmiller@example.net', ' Iceland', ' University of Akureyri', ' PhD'),
VALUES  ('gabriellarson@hotmail.com', ' Monaco', ' University of Southern Europe (Monaco Business School)', ' Masters'),
VALUES  ('gabriellarson@hotmail.com', ' Montenegro', ' University of Montenegro', ' PhD'),
VALUES  ('nicoleholland@example.com', ' Papua New Guinea', ' Pacific Adventist University', ' Bachelors'),
VALUES  ('nicoleholland@example.com', ' India', ' Chaudhary Charan Singh Haryana Agricultural University', ' Masters'),
VALUES  ('nicoleholland@example.com', ' Faroe Islands', ' University of the Faroe Islands', ' PhD'),
VALUES  ('allisoncross@gmail.com', ' Mauritius', ' University of Technology', ' Bachelors'),
VALUES  ('allisoncross@gmail.com', ' Georgia', ' Tbilisi Pedagogical University', ' Masters'),
VALUES  ('laurajones@example.com', ' Georgia', ' Tbilisi State Medical University', ' Bachelors'),
VALUES  ('laurajones@example.com', ' United Arab Emirates', ' Alhosn University', ' Masters'),
VALUES  ('jodyparker@example.com', ' Uganda', ' Nkumba University', ' Bachelors'),
VALUES  ('jodyparker@example.com', ' Bulgaria', ' Military University Shoumen', ' Masters'),
VALUES  ('michelleanthony@example.net', ' Greece', ' Dimocritus University of Thrace', ' Bachelors'),
VALUES  ('michelleanthony@example.net', ' Lesotho', ' National University of Lesotho', ' Masters'),
VALUES  ('michelleanthony@example.net', ' Haiti', ' American University of the Caribbean', ' PhD'),
VALUES  ('kevintanner@example.com', ' Philippines', ' Don Mariano Marcos Memorial State University', ' Bachelors'),
VALUES  ('adamwilliams@example.net', ' Switzerland', ' University of Zurich', ' Bachelors'),
VALUES  ('adamwilliams@example.net', ' Costa Rica', ' University for Peace', ' Masters'),
VALUES  ('jessicacallahan@hotmail.com', ' Taiwan', ' Shih Chien University', ' Bachelors'),
VALUES  ('jessicacallahan@hotmail.com', ' Belarus', ' European Humanities University', ' Masters'),
VALUES  ('tiffanymartinez@gmail.com', ' Tunisia', ' University of Aviation and Technology', ' Bachelors'),
VALUES  ('tiffanymartinez@gmail.com', ' Israel', ' University of Haifa', ' Masters'),
VALUES  ('amandaandrews@example.net', ' United Arab Emirates', ' Jumeira University', ' Bachelors'),
VALUES  ('amandaandrews@example.net', ' Maldives', ' Maldives National University', ' Masters'),
VALUES  ('jamesmedina@gmail.com', ' Serbia', ' University of Novi Sad', ' Bachelors'),
VALUES  ('jamesmedina@gmail.com', ' Slovakia', ' Pavol Jozef Safarik University in Kosice', ' Masters'),
VALUES  ('jamesmedina@gmail.com', ' Andorra', ' University of Andorra', ' PhD'),
VALUES  ('vanessagreen@example.net', ' Slovakia', ' Technical University in Kosice', ' Bachelors'),
VALUES  ('vanessagreen@example.net', ' Latvia', ' Daugavpils University', ' Masters'),
VALUES  ('vanessagreen@example.net', ' Netherlands', ' Dutch Delta University', ' PhD'),
VALUES  ('anthonybrewer@example.com', ' Suriname', ' Anton de Kom University', ' Bachelors'),
VALUES  ('melissaortega@example.net', ' Niue', ' St Clements University - Higher Education School', ' Bachelors'),
VALUES  ('melissaortega@example.net', ' Puerto Rico', ' Caribbean University', ' Masters'),
VALUES  ('melissaortega@example.net', ' Somalia', ' Maakhir University', ' PhD'),
VALUES  ('williamshepard@gmail.com', ' Belize', ' West Coast University (WCU)', ' Bachelors'),
VALUES  ('williamshepard@gmail.com', ' Benin', ' Espam Formation University', ' Masters'),
VALUES  ('williamshepard@gmail.com', ' Maldives', ' Maldives National University', ' PhD'),
VALUES  ('laurapace@hotmail.com', ' Qatar', ' University of Qatar', ' Bachelors'),
VALUES  ('laurapace@hotmail.com', ' Swaziland', ' University of Swaziland', ' Masters'),
VALUES  ('laurapace@hotmail.com', ' Norway', ' University of Tromsø', ' PhD'),
VALUES  ('stephaniebean@hotmail.com', ' Samoa', ' National University of Samoa', ' Bachelors'),
VALUES  ('stephaniebean@hotmail.com', ' Saudi Arabia', ' Prince Sultan University', ' Masters'),
VALUES  ('troybush@example.net', ' Norway', ' Agder University College', ' Bachelors'),
VALUES  ('troybush@example.net', ' Egypt', ' Helwan University', ' Masters'),
VALUES  ('troybush@example.net', ' Costa Rica', ' University for Peace', ' PhD'),
VALUES  ('carolhaynes@example.com', ' Kosovo', ' American University In Kosovo', ' Bachelors'),
VALUES  ('carolhaynes@example.com', ' Costa Rica', ' University for Peace', ' Masters'),
VALUES  ('angelshelton@example.com', ' Mauritius', ' University of Mauritius', ' Bachelors'),
VALUES  ('angelshelton@example.com', ' South Africa', ' University of Venda', ' Masters'),
VALUES  ('angelshelton@example.com', ' Benin', ' Houdegbe North American University Benin', ' PhD'),
VALUES  ('taylorgraham@hotmail.com', ' Jamaica', ' University of Technology Jamaica', ' Bachelors'),
VALUES  ('taylorgraham@hotmail.com', ' Bhutan', ' Royal University of Bhutan', ' Masters'),
VALUES  ('taylorgraham@hotmail.com', ' Kyrgyzstan', ' Kyrgyz Turkish  Manas University', ' PhD'),
VALUES  ('patriciariley@example.net', ' Thailand', ' Walailak University', ' Bachelors'),
VALUES  ('patriciariley@example.net', ' Albania', ' University of Gjirokstra "Eqerem Cabej"', ' Masters'),
VALUES  ('patriciariley@example.net', ' Philippines', ' Silliman University', ' PhD'),
VALUES  ('manuelserrano@example.com', ' Albania', ' University “Pavaresia” Vlore', ' Bachelors'),
VALUES  ('nicolelane@example.com', ' Spain', ' Bircham International University', ' Bachelors'),
VALUES  ('nicolelane@example.com', ' Switzerland', ' University of Applied Sciences Aargau', ' Masters'),
VALUES  ('colleenaguilar@example.com', ' Andorra', ' University of Andorra', ' Bachelors'),
VALUES  ('colleenaguilar@example.com', ' Slovenia', ' University of Nova Gorica', ' Masters'),
VALUES  ('colleenaguilar@example.com', ' Georgia', ' Tbilisi State Medical University', ' PhD'),
VALUES  ('heathercordova@example.com', ' Taiwan', ' Soochow University', ' Bachelors'),
VALUES  ('heathercordova@example.com', ' Jordan', ' Al-Isra University', ' Masters'),
VALUES  ('mrs.danielleyoung@example.com', ' Indonesia', ' Binus University', ' Bachelors'),
VALUES  ('mrs.danielleyoung@example.com', ' Benin', ' Espam Formation University', ' Masters'),
VALUES  ('derekharrell@example.com', ' Finland', ' Diaconia University of Applied Sciences', ' Bachelors'),
VALUES  ('derekharrell@example.com', ' Greece', ' University of Indianapolis in Athens', ' Masters'),
VALUES  ('dennismcdaniel@example.com', ' Samoa', ' University of the South Pacific School of Agriculture', ' Bachelors'),
VALUES  ('dennismcdaniel@example.com', ' Iran', ' Qom University of Medical Sciences', ' Masters'),
VALUES  ('dennismcdaniel@example.com', ' China', ' 2nd Military Medical University', ' PhD'),
VALUES  ('davidthornton@example.com', ' Cyprus', ' Girne American University', ' Bachelors'),
VALUES  ('davidthornton@example.com', ' Suriname', ' Anton de Kom University', ' Masters'),
VALUES  ('craigrobinson@example.com', ' Myanmar', ' Technological University (Myitkyina)', ' Bachelors'),
VALUES  ('craigrobinson@example.com', ' Taiwan', ' National Taipei University of Technology', ' Masters'),
VALUES  ('timothymartin@gmail.com', ' Puerto Rico', ' Caribbean University', ' Masters'),
VALUES  ('kevinwilliams@gmail.com', ' Morocco', ' Al Akhawayn University', ' Bachelors'),
VALUES  ('kevinwilliams@gmail.com', ' Panama', ' Floret Global University', ' Masters'),
VALUES  ('derekrichardson@gmail.com', ' Cameroon', ' Bamenda University of Science & Technology', ' Masters'),
VALUES  ('codynguyen@example.net', ' Greece', ' National Technical University of Athens', ' Bachelors'),
VALUES  ('codynguyen@example.net', ' Kuwait', ' Gulf University for Science and Technology', ' Masters'),
VALUES  ('codynguyen@example.net', ' Monaco', ' University of Southern Europe (Monaco Business School)', ' PhD'),
VALUES  ('hannahhall@hotmail.com', ' North Macedonia', ' State University of Tetova', ' Bachelors'),
VALUES  ('hannahhall@hotmail.com', ' Iraq', ' Al Mamon University College', ' Masters'),
VALUES  ('hannahhall@hotmail.com', ' Armenia', ' Armenian State University of Economics', ' PhD'),
VALUES  ('crystalkim@example.net', ' Monaco', ' University of Southern Europe (Monaco Business School)', ' Bachelors'),
VALUES  ('andreagilmoremd@example.com', ' Bosnia and Herzegovina', ' University of Sarajevo', ' Bachelors'),
VALUES  ('andreagilmoremd@example.com', ' Mexico', ' Westhill University', ' Masters'),
VALUES  ('elizabethhubbard@example.net', ' Belarus', ' Belarussian State Medical University', ' Bachelors'),
VALUES  ('elizabethhubbard@example.net', ' Denmark', ' Technical University of Denmark', ' Masters'),
VALUES  ('elizabethhubbard@example.net', ' Italy', ' Higher School of University and Advanced Studies Pisa', ' PhD'),
VALUES  ('jenniferwilkerson@gmail.com', ' Turks and Caicos Islands', ' Charisma University', ' Bachelors'),
VALUES  ('jenniferwilkerson@gmail.com', ' Guam', ' University of Guam', ' Masters'),
VALUES  ('paulashaffer@example.com', ' Namibia', ' International University of Management', ' Bachelors'),
VALUES  ('paulashaffer@example.com', ' Macao', ' University of Saint Joseph', ' Masters'),
VALUES  ('paulashaffer@example.com', ' Liberia', ' University of Liberia', ' PhD'),
VALUES  ('kevinholmes@example.com', ' Saint Kitts and Nevis', ' Ross University Caribbean School of Veterinary Medicine', ' Bachelors'),
VALUES  ('kevinholmes@example.com', ' Iceland', ' Technological University of Iceland', ' Masters'),
VALUES  ('kevinholmes@example.com', ' Montenegro', ' University of Montenegro', ' PhD'),
VALUES  ('brandoncompton@example.net', ' New Zealand', ' Victoria University of Wellington', ' Bachelors'),
VALUES  ('brandoncompton@example.net', ' Malawi', ' Malawi University of Business and Applied Sciences', ' Masters'),
VALUES  ('brandoncompton@example.net', ' Nigeria', ' Nigerian Turkish Nile University', ' PhD'),
VALUES  ('arianagreer@hotmail.com', ' Yemen', ' Saba University', ' Bachelors'),
VALUES  ('arianagreer@hotmail.com', ' South Africa', ' Durban University of Technology', ' Masters'),
VALUES  ('arianagreer@hotmail.com', ' Israel', ' Bar-Ilan University', ' PhD'),
VALUES  ('kimberlypatton@example.com', ' Morocco', ' Al Akhawayn University', ' Bachelors'),
VALUES  ('kimberlypatton@example.com', ' South Sudan', ' University of Juba', ' Masters'),
VALUES  ('bethmanning@hotmail.com', ' Guyana', ' Gemsville Technical University', ' Bachelors'),
VALUES  ('bethmanning@hotmail.com', ' Namibia', ' University of Namibia', ' Masters'),
VALUES  ('rubenrobbins@example.net', ' Portugal', ' European University Portugal', ' Bachelors'),
VALUES  ('rubenrobbins@example.net', ' Saint Kitts and Nevis', " St Theresa's Medical University", ' Masters'),
VALUES  ('kellydavis@example.net', ' Iran', ' Kar University', ' Bachelors'),
VALUES  ('kellydavis@example.net', ' New Zealand', ' University of Auckland', ' Masters'),
VALUES  ('joelsmith@gmail.com', ' Andorra', ' University of Andorra', ' Bachelors'),
VALUES  ('joelsmith@gmail.com', ' Montenegro', ' University of Montenegro', ' Masters'),
VALUES  ('staceypearson@gmail.com', ' Zimbabwe', ' Midlands State University', ' Bachelors'),
VALUES  ('staceypearson@gmail.com', ' Turkey', ' Bingol University', ' Masters'),
VALUES  ('billysalasdvm@gmail.com', ' Turkey', ' Nevsehir Haci Bektas Veli University', ' Bachelors'),
VALUES  ('billysalasdvm@gmail.com', ' Somalia', ' Benadir University', ' Masters'),
VALUES  ('davidsampson@example.com', ' Belgium', ' European Carolus Magnus University', ' Bachelors'),
VALUES  ('davidsampson@example.com', ' Botswana', ' ABM University College', ' Masters'),
VALUES  ('emmasolomon@example.net', ' Albania', ' University of Korca "Fan Noli"', ' Bachelors'),
VALUES  ('emmasolomon@example.net', " Lao People's Democratic Republic", ' National University of Laos', ' Masters'),
VALUES  ('emmasolomon@example.net', ' Switzerland', ' HTW Chur - University of Applied Sciences HTW Chur', ' PhD'),
VALUES  ('lesliemadden@example.com', ' Russian Federation', ' Petrozavodsk State University', ' Bachelors'),
VALUES  ('lesliemadden@example.com', ' Congo', ' University Marien Ngouabi Brazzaville', ' Masters'),
VALUES  ('lesliemadden@example.com', ' Australia', ' Victoria University', ' PhD'),
VALUES  ('kylebates@example.com', ' Nepal', ' Purbanchal University', ' Bachelors'),
VALUES  ('kylebates@example.com', ' Faroe Islands', ' University of the Faroe Islands', ' PhD'),
VALUES  ('carlyturner@gmail.com', ' Australia', ' Australian National University', ' Bachelors'),
VALUES  ('carlyturner@gmail.com', ' Libya', ' Al-Asmarya University for Islamic Studies', ' Masters'),
VALUES  ('sophiaholden@example.net', ' Rwanda', ' National University of Rwanda', ' Bachelors'),
VALUES  ('sophiaholden@example.net', ' Hong Kong', ' Chinese University of Hong Kong', ' PhD'),
VALUES  ('parkerbuckley@hotmail.com', ' Cambodia', ' Royal University of Fine Arts', ' Bachelors'),
VALUES  ('parkerbuckley@hotmail.com', ' United States', ' Harvard University', ' Masters'),
VALUES  ('jamesyoung@example.net', ' Solomon Islands', ' University of the South Pacific', ' Masters'),
VALUES  ('douglascase@gmail.com', ' Czech Republic', ' University of Pardubice', ' Bachelors'),
VALUES  ('douglascase@gmail.com', ' Papua New Guinea', ' Papua New Guinea University of Technology', ' Masters'),
VALUES  ('peggyhess@example.com', ' Iraq', ' Al Mamon University College', ' Bachelors'),
VALUES  ('peggyhess@example.com', ' Australia', ' University of Newcastle', ' Masters'),
VALUES  ('peggyhess@example.com', ' Singapore', ' Singapore Management University', ' PhD'),
VALUES  ('franciswilson@example.com', ' Niue', ' St Clements University - Higher Education School', ' Bachelors'),
VALUES  ('franciswilson@example.com', ' Faroe Islands', ' University of the Faroe Islands', ' Masters'),
VALUES  ('jenniferbrown@example.com', ' Rwanda', ' Kigali Independent University', ' Bachelors'),
VALUES  ('jenniferbrown@example.com', ' Seychelles', ' University of Seychelles', ' Masters'),
VALUES  ('jenniferbrown@example.com', ' Oman', ' Dhofar University', ' PhD'),
VALUES  ('lisabarnes@gmail.com', ' Thailand', ' Lampang Rajabhat University', ' Bachelors'),
VALUES  ('daniellechavez@example.net', ' Hong Kong', ' Hong Kong Baptist University', ' Bachelors'),
VALUES  ('daniellechavez@example.net', ' North Macedonia', ' State University of Tetova', ' Masters'),
VALUES  ('daniellechavez@example.net', ' Papua New Guinea', ' Pacific Adventist University', ' PhD'),
VALUES  ('eduardoburns@example.net', ' Lesotho', ' National University of Lesotho', ' Bachelors'),
VALUES  ('eduardoburns@example.net', ' Myanmar', ' Technological University (Kyaukse)', ' Masters'),
VALUES  ('troymorrison@gmail.com', ' Congo', ' University Marien Ngouabi Brazzaville', ' Bachelors'),
VALUES  ('troymorrison@gmail.com', ' Jamaica', ' Northern Caribbean University', ' PhD'),
VALUES  ('scottmiller@gmail.com', ' Zimbabwe', ' Zimbabwe Open University', ' Bachelors'),
VALUES  ('scottmiller@gmail.com', ' Jamaica', ' Northern Caribbean University', ' Masters'),
VALUES  ('cynthiabailey@hotmail.com', ' Indonesia', ' Duta Bangsa University', ' Bachelors'),
VALUES  ('cynthiabailey@hotmail.com', ' Antigua and Barbuda', ' University of Health Sciences Antigua', ' Masters'),
VALUES  ('cynthiabailey@hotmail.com', ' Dominica', ' New World University', ' PhD'),
VALUES  ('jackwilliams@example.com', ' Sri Lanka', ' Kotelawala Defence University', ' Bachelors'),
VALUES  ('jackwilliams@example.com', ' Cameroon', ' Bamenda University of Science & Technology', ' Masters'),
VALUES  ('jackwilliams@example.com', ' Fiji', ' Fiji National University', ' PhD'),
VALUES  ('oscarcole@example.com', ' Brunei Darussalam', ' University of Brunei Darussalam', ' Bachelors'),
VALUES  ('oscarcole@example.com', ' Solomon Islands', ' University of the South Pacific', ' Masters'),
VALUES  ('jonathantaylor@gmail.com', ' Saint Vincent and the Grenadines', ' Trinity University School of Medicine', ' Bachelors'),
VALUES  ('jonathantaylor@gmail.com', ' Andorra', ' University of Andorra', ' Masters'),
VALUES  ('tracyrodriguez@hotmail.com', ' Kosovo', ' American University In Kosovo', ' Bachelors'),
VALUES  ('tracyrodriguez@hotmail.com', ' Malawi', ' Catholic University of Malawi', ' Masters'),
VALUES  ('tracyrodriguez@hotmail.com', ' Belarus', ' Gomel State Medical University', ' PhD'),
VALUES  ('jameswilliams@example.com', ' Taiwan', ' Aletheia University', ' Bachelors'),
VALUES  ('jameswilliams@example.com', ' Indonesia', ' Swiss German University', ' Masters'),
VALUES  ('thomasfisher@example.net', ' Rwanda', ' National University of Rwanda', ' Bachelors'),
VALUES  ('thomasfisher@example.net', ' Thailand', ' Hatyai University', ' Masters'),
VALUES  ('ashleysims@hotmail.com', ' Bhutan', ' Royal University of Bhutan', ' Bachelors'),
VALUES  ('ashleysims@hotmail.com', ' Bulgaria', ' Medical University Pleven', ' Masters'),
VALUES  ('todddavis@example.net', ' United States', ' Southern University and A&M College', ' Bachelors'),
VALUES  ('todddavis@example.net', ' Slovakia', ' Law University of Bratislava', ' Masters'),
VALUES  ('tanyagarcia@example.net', ' Saint Vincent and the Grenadines', ' Trinity University School of Medicine', ' Bachelors'),
VALUES  ('tanyagarcia@example.net', ' Andorra', ' University of Andorra', ' Masters'),
VALUES  ('sarawoods@example.com', ' Haiti', ' American University of the Caribbean', ' Bachelors'),
VALUES  ('sarawoods@example.com', ' Afghanistan', ' Herat University', ' Masters'),
VALUES  ('sarawoods@example.com', ' Puerto Rico', ' Caribbean University', ' PhD'),
VALUES  ('michelerice@example.net', ' Tonga', ' University of the South Pacific Centre', ' Bachelors'),
VALUES  ('michelerice@example.net', ' Rwanda', ' Kigali Independent University', ' Masters'),
VALUES  ('tinamoore@gmail.com', ' Georgia', ' International Blacksea University', ' Bachelors'),
VALUES  ('tinamoore@gmail.com', ' Finland', ' Lappeenranta University of Technology', ' Masters'),
VALUES  ('tinamoore@gmail.com', ' Cameroon', ' Bamenda University of Science & Technology', ' PhD'),
VALUES  ('johnnygrant@example.net', ' South Sudan', ' University of Northern Bahr El-Ghazal', ' Bachelors'),
VALUES  ('johnnygrant@example.net', ' Serbia', ' European University', ' Masters'),
VALUES  ('adampeterson@hotmail.com', ' United States', ' Purdue University Fort Wayne', ' Bachelors'),
VALUES  ('adampeterson@hotmail.com', ' North Macedonia', ' State University of Tetova', ' Masters'),
VALUES  ('katherinemendez@hotmail.com', ' Ukraine', ' Donetsk National Technical University', ' Bachelors'),
VALUES  ('katherinemendez@hotmail.com', ' Congo', ' University Marien Ngouabi Brazzaville', ' Masters'),
VALUES  ('jasonphillips@example.com', ' Trinidad and Tobago', ' University of the Southern Caribbean', ' Bachelors'),
VALUES  ('jasonphillips@example.com', ' Hungary', ' University of Pannonia', ' Masters'),
VALUES  ('lauralopez@hotmail.com', ' Costa Rica', ' University for Peace', ' Bachelors'),
VALUES  ('lauralopez@hotmail.com', ' Jordan', ' Jordan University of Science and Technology', ' Masters'),
VALUES  ('suzannevasquez@example.net', ' Libya', ' Sirte University', ' Bachelors'),
VALUES  ('suzannevasquez@example.net', ' Antigua and Barbuda', ' American University of Antigua', ' Masters'),
VALUES  ('kevinclements@hotmail.com', ' Turks and Caicos Islands', ' Charisma University', ' Bachelors'),
VALUES  ('kevinclements@hotmail.com', ' Samoa', ' National University of Samoa', ' Masters'),
VALUES  ('kevinclements@hotmail.com', ' Saudi Arabia', ' Yanbu University College', ' PhD'),
VALUES  ('erichernandez@gmail.com', ' Italy', ' University of Cassino', ' Bachelors'),
VALUES  ('erichernandez@gmail.com', ' Slovakia', ' University of SS. Cyril and Methodius in Trnava', ' Masters'),
VALUES  ('dr.hannahwashington@gmail.com', ' Lesotho', ' National University of Lesotho', ' Bachelors'),
VALUES  ('dr.hannahwashington@gmail.com', ' Congo', ' University Marien Ngouabi Brazzaville', ' Masters'),
VALUES  ('dr.hannahwashington@gmail.com', ' Hungary', ' University Medical School of Debrecen', ' PhD'),
VALUES  ('cindyrussell@example.net', ' Luxembourg', ' International University Institute of Luxembourg', ' Bachelors'),
VALUES  ('cindyrussell@example.net', ' Singapore', ' Singapore Management University', ' PhD'),
VALUES  ('carmenstokes@example.net', ' India', ' Biju Pattnaik University of Technology', ' Bachelors'),
VALUES  ('carmenstokes@example.net', ' Nigeria', ' Crawford University', ' Masters'),
VALUES  ('carmenstokes@example.net', ' South Sudan', ' University of Northern Bahr El-Ghazal', ' PhD'),
VALUES  ('lauraflynn@example.com', ' South Africa', ' Sefako Makgatho Health Sciences University', ' Bachelors'),
VALUES  ('lauraflynn@example.com', ' Thailand', ' Chulalongkorn University', ' Masters'),
VALUES  ('lauraflynn@example.com', ' Portugal', ' European University Portugal', ' PhD'),
VALUES  ('nicholaswilliamsjr.@hotmail.com', ' Kenya', ' Uzima University College', ' Bachelors'),
VALUES  ('nicholaswilliamsjr.@hotmail.com', ' Namibia', ' University of Namibia', ' Masters'),
VALUES  ('sherrymills@hotmail.com', ' Oman', ' Sur University College', ' Bachelors'),
VALUES  ('sherrymills@hotmail.com', ' Norway', " Norway's Information Technology University College", ' Masters'),
VALUES  ('lindamorris@example.com', ' Egypt', ' Suez Canal University', ' Masters'),
VALUES  ('lindamorris@example.com', ' Australia', ' Australian National University', ' PhD'),
VALUES  ('jessemays@example.com', ' Switzerland', ' Zurich University of Applied Sciences Winterthur', ' Bachelors'),
VALUES  ('jessemays@example.com', ' Mauritius', ' University of Mauritius', ' Masters'),
VALUES  ('jasonjuarez@hotmail.com', ' Yemen', ' Saba University', ' Bachelors'),
VALUES  ('jasonjuarez@hotmail.com', ' Faroe Islands', ' University of the Faroe Islands', ' Masters'),
VALUES  ('lauraprice@example.net', ' Lebanon', ' Arab Open University', ' Bachelors'),
VALUES  ('lauraprice@example.net', ' Finland', ' University of Kuopio', ' Masters'),
VALUES  ('patriciarichardson@example.com', ' Panama', ' West Coast University (WCU)', ' Bachelors'),
VALUES  ('patriciarichardson@example.com', ' Cameroon', ' Bamenda University of Science & Technology', ' Masters'),
VALUES  ('williamtaylor@example.net', ' Zambia', ' University of Zambia', ' Bachelors'),
VALUES  ('williamtaylor@example.net', ' Tajikistan', ' Tajik Agrarian University', ' Masters'),
VALUES  ('williamtaylor@example.net', ' Switzerland', ' University of Basel', ' PhD'),
VALUES  ('matthewbryan@example.net', ' Tajikistan', ' Tajik National University', ' Bachelors'),
VALUES  ('matthewbryan@example.net', ' Trinidad and Tobago', ' University of the West Indies St. Augustine', ' Masters'),
VALUES  ('matthewbryan@example.net', ' Taiwan', ' Hsuan Chuang University', ' PhD'),
VALUES  ('lisagreen@gmail.com', ' Sudan', ' Omdurman Islamic University', ' Bachelors'),
VALUES  ('lisagreen@gmail.com', ' Armenia', ' Eurasia International University', ' Masters'),
VALUES  ('kristenwatsondds@example.com', ' Ghana', ' Central University College', ' Bachelors'),
VALUES  ('kristenwatsondds@example.com', ' South Africa', ' Sol Plaatje University', ' Masters'),
VALUES  ('kristenwatsondds@example.com', ' Finland', ' Diaconia University of Applied Sciences', ' PhD'),
VALUES  ('rebeccabowman@hotmail.com', ' Tunisia', ' University of Aviation and Technology', ' Bachelors'),
VALUES  ('rebeccabowman@hotmail.com', ' Bhutan', ' Royal University of Bhutan', ' Masters'),
VALUES  ('rebeccabowman@hotmail.com', ' Botswana', ' Botswana International University of Science & Technology', ' PhD'),
VALUES  ('mr.connorpugh@example.com', ' Viet Nam', ' Hue University of Agriculture and Forestry', ' Masters'),
VALUES  ('wesleymiranda@example.net', ' Hong Kong', ' The Education University of Hong Kong', ' Bachelors'),
VALUES  ('davidscott@hotmail.com', ' Pakistan', ' Isra University', ' Bachelors'),
VALUES  ('davidscott@hotmail.com', ' Myanmar', ' Technological University (Pinlon)', ' Masters'),
VALUES  ('courtneyanderson@example.net', ' Haiti', ' American University of the Caribbean', ' Bachelors'),
VALUES  ('courtneyanderson@example.net', ' Afghanistan', ' Paktia University', ' Masters'),
VALUES  ('juliesummers@example.com', ' Slovenia', ' University of Ljubljana', ' Bachelors'),
VALUES  ('juliesummers@example.com', ' Puerto Rico', ' Caribbean University', ' Masters'),
VALUES  ('juliesummers@example.com', ' Thailand', ' Lampang Rajabhat University', ' PhD'),
VALUES  ('michaelgreen@example.com', ' Mexico', ' Westhill University', ' Bachelors'),
VALUES  ('michaelgreen@example.com', ' Burundi', ' Hope Africa University', ' Masters'),
VALUES  ('michaelgreen@example.com', ' United States', ' Georgia Southwestern State University', ' PhD'),
VALUES  ('tracyphelps@hotmail.com', ' Ireland', ' University College Cork', ' Bachelors'),
VALUES  ('tracyphelps@hotmail.com', ' Maldives', ' Maldives National University', ' Masters'),
VALUES  ('jeremytorres@gmail.com', ' Viet Nam', ' Hanoi University of Science and Technology', ' Bachelors'),
VALUES  ('vincentsantos@example.com', ' Cyprus', ' European University Cyprus', ' Bachelors'),
VALUES  ('vincentsantos@example.com', ' Trinidad and Tobago', ' University of the Southern Caribbean', ' Masters'),
VALUES  ('dr.davidstevensdds@hotmail.com', ' United Kingdom', ' University of Bristol', ' Bachelors'),
VALUES  ('dr.davidstevensdds@hotmail.com', ' Costa Rica', ' University for Peace', ' Masters'),
VALUES  ('amydominguez@hotmail.com', ' Turkey', ' Antalya international University', ' Masters'),
VALUES  ('amydominguez@hotmail.com', ' Antigua and Barbuda', ' American University of Antigua', ' PhD'),
VALUES  ('cindymarsh@example.com', ' Greenland', ' University of Greenland', ' Bachelors'),
VALUES  ('cindymarsh@example.com', ' Cambodia', ' Norton University', ' Masters'),
VALUES  ('cindymarsh@example.com', ' Brunei Darussalam', ' University of Brunei Darussalam', ' PhD'),
VALUES  ('ivanrichardson@example.com', ' Qatar', ' Northwestern University In Qatar', ' Bachelors'),
VALUES  ('ivanrichardson@example.com', ' Bulgaria', ' University of Food Technology', ' Masters'),
VALUES  ('ivanrichardson@example.com', ' Saint Vincent and the Grenadines', ' Trinity University School of Medicine', ' PhD'),
VALUES  ('johnboyd@hotmail.com', ' Swaziland', ' University of Swaziland', ' Bachelors'),
VALUES  ('johnboyd@hotmail.com', ' Malaysia', ' Nilai University College', ' Masters'),
VALUES  ('michaelbarnes@hotmail.com', ' Czech Republic', ' Anglo-American University', ' Bachelors'),
VALUES  ('michaelbarnes@hotmail.com', ' Japan', ' Meiji Gakuin University', ' Masters'),
VALUES  ('garyjackson@example.net', ' Liberia', ' University of Liberia', ' Bachelors'),
VALUES  ('garyjackson@example.net', ' Malawi', ' Lilongwe University of Agriculture and Natural Resources', ' Masters'),
VALUES  ('christopherflowers@hotmail.com', ' Zimbabwe', ' Zimbabwe Ezekiel Guti University', ' Bachelors'),
VALUES  ('christopherflowers@hotmail.com', ' Mexico', ' Westhill University', ' Masters'),
VALUES  ('christopherflowers@hotmail.com', ' Guyana', ' Texila American University', ' PhD'),
VALUES  ('michaelthomas@example.net', ' Kenya', ' Dedan Kimathi University of Technology', ' Masters'),
VALUES  ('kylebrown@example.net', ' South Sudan', ' University of Northern Bahr El-Ghazal', ' Bachelors'),
VALUES  ('kylebrown@example.net', ' Brunei Darussalam', ' University of Brunei Darussalam', ' Masters'),
VALUES  ('kylebrown@example.net', ' Macao', ' University of Saint Joseph', ' PhD'),
VALUES  ('sarahfischer@hotmail.com', ' Swaziland', ' University of Swaziland', ' Bachelors'),
VALUES  ('sarahfischer@hotmail.com', ' Mongolia', ' University of the Humanities', ' Masters'),
VALUES  ('sarahfischer@hotmail.com', ' Kosovo', ' American University In Kosovo', ' PhD'),
VALUES  ('ashleymorrison@example.com', ' Saudi Arabia', ' King Saud bin Abdulaziz University for Health Sciences', ' Bachelors'),
VALUES  ('ashleymorrison@example.com', ' Kosovo', ' American University In Kosovo', ' Masters'),
VALUES  ('ashleymorrison@example.com', ' Saint Lucia', ' Spartan University of Health Sciences', ' PhD'),
VALUES  ('kathymaldonado@example.com', ' Iceland', ' University of Akureyri', ' Bachelors'),
VALUES  ('kathymaldonado@example.com', ' Rwanda', ' Kigali Independent University', ' PhD'),
VALUES  ('karenmills@example.com', ' Niue', ' St Clements University - Higher Education School', ' Bachelors'),
VALUES  ('dr.jennifermorris@example.net', ' Jordan', ' Amman Arab University for Higher Studies', ' Bachelors'),
VALUES  ('dr.jennifermorris@example.net', ' Bhutan', ' Royal University of Bhutan', ' Masters'),
VALUES  ('dr.jennifermorris@example.net', ' Hong Kong', ' The Hang Seng University of Hong Kong', ' PhD'),
VALUES  ('katherinepadilla@hotmail.com', ' Canada', " St. Mary's University", ' Bachelors'),
VALUES  ('katherinepadilla@hotmail.com', ' Malta', ' University of Malta', ' Masters'),
VALUES  ('stephaniehampton@example.com', ' Bahrain', ' The Kingdom University', ' Bachelors'),
VALUES  ('stephaniehampton@example.com', ' Norway', ' University of Oslo', ' Masters'),
VALUES  ('stephaniehampton@example.com', ' Suriname', ' Anton de Kom University', ' PhD'),
VALUES  ('cherylharper@gmail.com', ' Solomon Islands', ' University of the South Pacific', ' Bachelors'),
VALUES  ('cherylharper@gmail.com', ' China', ' Hebei University', ' Masters'),
VALUES  ('valeriewilson@hotmail.com', ' Latvia', ' Vidzeme University College', ' Bachelors'),
VALUES  ('valeriewilson@hotmail.com', ' India', ' Punjabi University Patiala', ' Masters'),
VALUES  ('troybrown@example.com', ' Malawi', ' University of Malawi | Old', ' Bachelors'),
VALUES  ('troybrown@example.com', ' Libya', ' Zawiya University', ' Masters'),
VALUES  ('antoniohorn@example.net', ' Tunisia', ' University of Aviation and Technology', ' Bachelors'),
VALUES  ('antoniohorn@example.net', ' Benin', ' Espam Formation University', ' Masters'),
VALUES  ('antoniohorn@example.net', ' Azerbaijan', ' Azerbaijan State Pedagogic University', ' PhD'),
VALUES  ('curtissingleton@example.net', ' Canada', ' Mount Saint Vincent University', ' Bachelors'),
VALUES  ('curtissingleton@example.net', ' Kyrgyzstan', ' Kyrgyz National Agrarian University', ' Masters'),
VALUES  ('joannbarnett@example.net', ' Oman', ' University of Nizwa', ' Bachelors'),
VALUES  ('joannbarnett@example.net', ' Kuwait', ' Gulf University for Science and Technology', ' Masters'),
VALUES  ('maxsmith@example.com', ' Kuwait', ' American University of Kuwait', ' Bachelors'),
VALUES  ('maxsmith@example.com', ' Japan', ' Kure University', ' Masters'),
VALUES  ('lesliebuchanan@gmail.com', ' Croatia', ' University of Pula', ' Bachelors'),
VALUES  ('lesliebuchanan@gmail.com', ' Taiwan', ' National Taipei University', ' Masters'),
VALUES  ('lesliebuchanan@gmail.com', ' Faroe Islands', ' University of the Faroe Islands', ' PhD'),
VALUES  ('josephgomez@example.com', ' Netherlands', ' Leiden University', ' Bachelors'),
VALUES  ('josephgomez@example.com', ' Indonesia', ' Binus University', ' Masters'),
VALUES  ('johnharris@example.com', ' Rwanda', ' Adventist University of Central Africa', ' Bachelors'),
VALUES  ('johnharris@example.com', ' Kenya', ' Masinde Muliro University of Science and Technology', ' Masters'),
VALUES  ('johnharris@example.com', ' Serbia', ' Metropolitan University', ' PhD'),
VALUES  ('peterallen@hotmail.com', ' Sri Lanka', ' Uva Wellassa University', ' Bachelors'),
VALUES  ('peterallen@hotmail.com', ' Azerbaijan', ' Azerbaijan University of Architecture and Construction', ' Masters'),
VALUES  ('jeffreyshelton@example.com', ' Italy', ' University of Reggio Calabria', ' Bachelors'),
VALUES  ('jeffreyshelton@example.com', ' Solomon Islands', ' University of the South Pacific', ' Masters'),
VALUES  ('jeffreyshelton@example.com', ' Croatia', ' University of Rijeka', ' PhD'),
VALUES  ('jamiewoods@example.net', ' Tajikistan', ' Tajik Agrarian University', ' Bachelors'),
VALUES  ('jamiewoods@example.net', ' Latvia', ' Latvia University of Life Sciences and Technologies', ' Masters'),
VALUES  ('michellepeck@gmail.com', ' Iraq', ' University of Mustansiriyah', ' Bachelors'),
VALUES  ('michellepeck@gmail.com', ' Mauritius', ' University of Technology', ' Masters'),
VALUES  ('annahenderson@example.net', ' Afghanistan', ' Takhar University', ' Bachelors'),
VALUES  ('annahenderson@example.net', ' Faroe Islands', ' University of the Faroe Islands', ' Masters'),
VALUES  ('saraford@example.com', ' Puerto Rico', ' Caribbean University', ' Bachelors'),
VALUES  ('saraford@example.com', ' Uganda', ' Mountains of the Moon University', ' Masters'),
VALUES  ('annwhite@example.com', ' Guyana', ' Gemsville Technical University', ' Bachelors'),
VALUES  ('annwhite@example.com', ' Macao', ' University of Macau', ' PhD'),
VALUES  ('andrewortiz@gmail.com', ' Oman', ' Sohar University', ' Bachelors'),
VALUES  ('andrewortiz@gmail.com', ' Czech Republic', ' Palacký University Olomouc', ' Masters'),
VALUES  ('andrewortiz@gmail.com', ' Haiti', ' American University of the Caribbean', ' PhD'),
VALUES  ('jennifermay@example.net', ' Slovakia', ' Comenius University in Bratislava', ' Bachelors'),
VALUES  ('rachaeltaylor@example.com', ' Croatia', ' University of Dubrovnik', ' Bachelors'),
VALUES  ('rachaeltaylor@example.com', ' Tonga', ' University of the South Pacific Centre', ' Masters'),
VALUES  ('timothystevens@example.net', ' Romania', ' Valahia University of Targoviste', ' Bachelors'),
VALUES  ('timothystevens@example.net', ' Jordan', ' Jerash Private University', ' Masters'),
VALUES  ('timothystevens@example.net', ' Qatar', ' University of Qatar', ' PhD'),
VALUES  ('derekturner@example.net', ' Morocco', ' Al Akhawayn University', ' Bachelors'),
VALUES  ('amywang@hotmail.com', ' Grenada', " St. George's University", ' Bachelors'),
VALUES  ('amywang@hotmail.com', ' Botswana', ' University of Botswana', ' Masters'),